# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from payload.manager.admin.v1 import stats_pb2 as payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2


class PayloadAdminServiceStub(object):
  """
  Operational inspection API.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Stats = channel.unary_unary(
        '/payload.manager.services.v1.PayloadAdminService/Stats',
        request_serializer=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2.StatsRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2.StatsResponse.FromString,
        )


class PayloadAdminServiceServicer(object):
  """
  Operational inspection API.
  """

  def Stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PayloadAdminServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Stats': grpc.unary_unary_rpc_method_handler(
          servicer.Stats,
          request_deserializer=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2.StatsRequest.FromString,
          response_serializer=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2.StatsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payload.manager.services.v1.PayloadAdminService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
