# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import ring_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payload/manager/services/v1/payload_ring_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayloadRingServiceStub(object):
    """
    PayloadRingService — TIER_RAM_RING data-plane RPCs.

    The ring tier is position-addressed (slot_idx in a ring) rather than
    UUID-addressed. Producers acquire a slot, write into the
    PM-allocated /dev/shm region, and commit. Consumers map the ring
    once at startup (learning every slot's shm name + capacity), and
    per capture lease the slot index carried in the upstream domain
    event, reading via their cached pointer.

    Distinct from PayloadCatalogService/PayloadDataService because the
    ring tier has no per-call allocate / commit / promote / spill /
    metadata lifecycle — slots are pre-allocated at ring-definition
    time and recycled in place. Combining the APIs would either
    bifurcate the existing UUID-shaped messages with ring-only fields
    or force ring callers to set meaningless UUIDs.

    Ring definitions themselves are static config (see
    RuntimeConfig.storage.ring_tier in
    config/service/v1/payload_manager.proto) — PM creates the slots at
    startup, this service only manages slot reservation / lease state.

    --- Producer ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireRingSlot = channel.unary_unary(
                '/payload.manager.services.v1.PayloadRingService/AcquireRingSlot',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotResponse.FromString,
                _registered_method=True)
        self.CommitRingSlot = channel.unary_unary(
                '/payload.manager.services.v1.PayloadRingService/CommitRingSlot',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotResponse.FromString,
                _registered_method=True)
        self.MapRing = channel.unary_unary(
                '/payload.manager.services.v1.PayloadRingService/MapRing',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingResponse.FromString,
                _registered_method=True)
        self.LeaseRingSlot = channel.unary_unary(
                '/payload.manager.services.v1.PayloadRingService/LeaseRingSlot',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotResponse.FromString,
                _registered_method=True)
        self.ReleaseRingSlot = channel.unary_unary(
                '/payload.manager.services.v1.PayloadRingService/ReleaseRingSlot',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.ReleaseRingSlotRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PayloadRingServiceServicer(object):
    """
    PayloadRingService — TIER_RAM_RING data-plane RPCs.

    The ring tier is position-addressed (slot_idx in a ring) rather than
    UUID-addressed. Producers acquire a slot, write into the
    PM-allocated /dev/shm region, and commit. Consumers map the ring
    once at startup (learning every slot's shm name + capacity), and
    per capture lease the slot index carried in the upstream domain
    event, reading via their cached pointer.

    Distinct from PayloadCatalogService/PayloadDataService because the
    ring tier has no per-call allocate / commit / promote / spill /
    metadata lifecycle — slots are pre-allocated at ring-definition
    time and recycled in place. Combining the APIs would either
    bifurcate the existing UUID-shaped messages with ring-only fields
    or force ring callers to set meaningless UUIDs.

    Ring definitions themselves are static config (see
    RuntimeConfig.storage.ring_tier in
    config/service/v1/payload_manager.proto) — PM creates the slots at
    startup, this service only manages slot reservation / lease state.

    --- Producer ---
    """

    def AcquireRingSlot(self, request, context):
        """
        Reserve the next available slot in `ring_id`. PM picks the slot
        (round-robin over slots whose refcount has hit zero since they
        were last committed); the returned (slot_idx, generation) is the
        triple the producer will write into the downstream event's
        RingSlotRef.

        Fails with RESOURCE_EXHAUSTED when no slot is available (every
        slot is currently leased by at least one consumer) and the ring's
        exhaustion_policy is DROP_NEW. With BLOCK the call waits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitRingSlot(self, request, context):
        """
        Publish the just-written slot. PM marks the slot ready-for-lease
        so consumers' LeaseRingSlot calls succeed. The producer publishes
        the downstream domain event (e.g. RadioCaptureEvent) on NATS
        carrying the RingSlotRef in parallel; consumers see the event
        and call LeaseRingSlot to take the read lease.

        Fails with FAILED_PRECONDITION if (slot_idx, generation) doesn't
        match the producer's last AcquireRingSlot — guards against
        double-commit or commits on stale handles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapRing(self, request, context):
        """--- Consumer ---


        One-time discovery on consumer startup. Returns the ring's slot
        count + per-slot shm names so the consumer can mmap (and, for GPU
        consumers, cudaHostRegister + cudaHostGetDevicePointer) every
        slot ahead of the hot path. The returned shm names are stable
        for the lifetime of the PM process; clients should not poll
        MapRing per-capture.

        Fails with NOT_FOUND if the ring isn't configured in PM's static
        config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaseRingSlot(self, request, context):
        """
        Bump the slot's refcount and grant a read lease. Lightweight —
        no bytes cross the wire, only the (ring_id, slot_idx, generation)
        triple and the returned opaque lease_id.

        Fails with FAILED_PRECONDITION if the generation no longer matches
        the slot's current generation (consumer was too slow, producer
        already recycled the slot). The consumer should skip this capture
        and wait for the next event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseRingSlot(self, request, context):
        """
        Drop the lease, decrement the slot's refcount. When the refcount
        reaches zero the slot is eligible for the producer's next
        AcquireRingSlot. Idempotent: releasing an already-released lease
        is a no-op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayloadRingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireRingSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireRingSlot,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotResponse.SerializeToString,
            ),
            'CommitRingSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitRingSlot,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotResponse.SerializeToString,
            ),
            'MapRing': grpc.unary_unary_rpc_method_handler(
                    servicer.MapRing,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingResponse.SerializeToString,
            ),
            'LeaseRingSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseRingSlot,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotResponse.SerializeToString,
            ),
            'ReleaseRingSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseRingSlot,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.ReleaseRingSlotRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payload.manager.services.v1.PayloadRingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payload.manager.services.v1.PayloadRingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayloadRingService(object):
    """
    PayloadRingService — TIER_RAM_RING data-plane RPCs.

    The ring tier is position-addressed (slot_idx in a ring) rather than
    UUID-addressed. Producers acquire a slot, write into the
    PM-allocated /dev/shm region, and commit. Consumers map the ring
    once at startup (learning every slot's shm name + capacity), and
    per capture lease the slot index carried in the upstream domain
    event, reading via their cached pointer.

    Distinct from PayloadCatalogService/PayloadDataService because the
    ring tier has no per-call allocate / commit / promote / spill /
    metadata lifecycle — slots are pre-allocated at ring-definition
    time and recycled in place. Combining the APIs would either
    bifurcate the existing UUID-shaped messages with ring-only fields
    or force ring callers to set meaningless UUIDs.

    Ring definitions themselves are static config (see
    RuntimeConfig.storage.ring_tier in
    config/service/v1/payload_manager.proto) — PM creates the slots at
    startup, this service only manages slot reservation / lease state.

    --- Producer ---
    """

    @staticmethod
    def AcquireRingSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadRingService/AcquireRingSlot',
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.AcquireRingSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitRingSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadRingService/CommitRingSlot',
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.CommitRingSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MapRing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadRingService/MapRing',
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.MapRingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaseRingSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadRingService/LeaseRingSlot',
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.LeaseRingSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseRingSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadRingService/ReleaseRingSlot',
            payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2.ReleaseRingSlotRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
