# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/services/v1/payload_catalog_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import lifecycle_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2
from payload.manager.runtime.v1 import tiering_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2
from payload.manager.catalog.v1 import catalog_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2
from payload.manager.catalog.v1 import lineage_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/services/v1/payload_catalog_service.proto',
  package='payload.manager.services.v1',
  syntax='proto3',
  serialized_pb=_b('\n9payload/manager/services/v1/payload_catalog_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a*payload/manager/runtime/v1/lifecycle.proto\x1a(payload/manager/runtime/v1/tiering.proto\x1a(payload/manager/catalog/v1/catalog.proto\x1a(payload/manager/catalog/v1/lineage.proto2\xdd\n\n\x15PayloadCatalogService\x12z\n\x0f\x41llocatePayload\x12\x32.payload.manager.runtime.v1.AllocatePayloadRequest\x1a\x33.payload.manager.runtime.v1.AllocatePayloadResponse\x12t\n\rCommitPayload\x12\x30.payload.manager.runtime.v1.CommitPayloadRequest\x1a\x31.payload.manager.runtime.v1.CommitPayloadResponse\x12K\n\x06\x44\x65lete\x12).payload.manager.runtime.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x12\x62\n\x07Promote\x12*.payload.manager.runtime.v1.PromoteRequest\x1a+.payload.manager.runtime.v1.PromoteResponse\x12\\\n\x05Spill\x12(.payload.manager.runtime.v1.SpillRequest\x1a).payload.manager.runtime.v1.SpillResponse\x12O\n\x08Prefetch\x12+.payload.manager.runtime.v1.PrefetchRequest\x1a\x16.google.protobuf.Empty\x12\x45\n\x03Pin\x12&.payload.manager.runtime.v1.PinRequest\x1a\x16.google.protobuf.Empty\x12I\n\x05Unpin\x12(.payload.manager.runtime.v1.UnpinRequest\x1a\x16.google.protobuf.Empty\x12S\n\nAddLineage\x12-.payload.manager.catalog.v1.AddLineageRequest\x1a\x16.google.protobuf.Empty\x12k\n\nGetLineage\x12-.payload.manager.catalog.v1.GetLineageRequest\x1a..payload.manager.catalog.v1.GetLineageResponse\x12\x8c\x01\n\x15UpdatePayloadMetadata\x12\x38.payload.manager.catalog.v1.UpdatePayloadMetadataRequest\x1a\x39.payload.manager.catalog.v1.UpdatePayloadMetadataResponse\x12\x9b\x01\n\x1a\x41ppendPayloadMetadataEvent\x12=.payload.manager.catalog.v1.AppendPayloadMetadataEventRequest\x1a>.payload.manager.catalog.v1.AppendPayloadMetadataEventResponse\x12q\n\x0cListPayloads\x12/.payload.manager.runtime.v1.ListPayloadsRequest\x1a\x30.payload.manager.runtime.v1.ListPayloadsResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DESCRIPTOR,payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.DESCRIPTOR,payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.DESCRIPTOR,payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOADCATALOGSERVICE = _descriptor.ServiceDescriptor(
  name='PayloadCatalogService',
  full_name='payload.manager.services.v1.PayloadCatalogService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=290,
  serialized_end=1663,
  methods=[
  _descriptor.MethodDescriptor(
    name='AllocatePayload',
    full_name='payload.manager.services.v1.PayloadCatalogService.AllocatePayload',
    index=0,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._ALLOCATEPAYLOADREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._ALLOCATEPAYLOADRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommitPayload',
    full_name='payload.manager.services.v1.PayloadCatalogService.CommitPayload',
    index=1,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._COMMITPAYLOADREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._COMMITPAYLOADRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='payload.manager.services.v1.PayloadCatalogService.Delete',
    index=2,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._DELETEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Promote',
    full_name='payload.manager.services.v1.PayloadCatalogService.Promote',
    index=3,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._PROMOTEREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._PROMOTERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Spill',
    full_name='payload.manager.services.v1.PayloadCatalogService.Spill',
    index=4,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._SPILLREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._SPILLRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Prefetch',
    full_name='payload.manager.services.v1.PayloadCatalogService.Prefetch',
    index=5,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._PREFETCHREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pin',
    full_name='payload.manager.services.v1.PayloadCatalogService.Pin',
    index=6,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._PINREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Unpin',
    full_name='payload.manager.services.v1.PayloadCatalogService.Unpin',
    index=7,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2._UNPINREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddLineage',
    full_name='payload.manager.services.v1.PayloadCatalogService.AddLineage',
    index=8,
    containing_service=None,
    input_type=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2._ADDLINEAGEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLineage',
    full_name='payload.manager.services.v1.PayloadCatalogService.GetLineage',
    index=9,
    containing_service=None,
    input_type=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2._GETLINEAGEREQUEST,
    output_type=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2._GETLINEAGERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePayloadMetadata',
    full_name='payload.manager.services.v1.PayloadCatalogService.UpdatePayloadMetadata',
    index=10,
    containing_service=None,
    input_type=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2._UPDATEPAYLOADMETADATAREQUEST,
    output_type=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2._UPDATEPAYLOADMETADATARESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppendPayloadMetadataEvent',
    full_name='payload.manager.services.v1.PayloadCatalogService.AppendPayloadMetadataEvent',
    index=11,
    containing_service=None,
    input_type=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2._APPENDPAYLOADMETADATAEVENTREQUEST,
    output_type=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2._APPENDPAYLOADMETADATAEVENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListPayloads',
    full_name='payload.manager.services.v1.PayloadCatalogService.ListPayloads',
    index=12,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._LISTPAYLOADSREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2._LISTPAYLOADSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYLOADCATALOGSERVICE)

DESCRIPTOR.services_by_name['PayloadCatalogService'] = _PAYLOADCATALOGSERVICE

# @@protoc_insertion_point(module_scope)
