# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import lease_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payload/manager/services/v1/payload_data_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayloadDataServiceStub(object):
    """
    High-frequency runtime data-plane operations.

    ResolveSnapshot: Returns the current placement descriptor for a payload
    (tier, location, state). This is an ADVISORY snapshot — the payload may
    move to a different tier or be deleted between this call and any subsequent
    read. Do NOT use this descriptor to access payload data directly. Use
    AcquireReadLease to obtain a stable, lease-protected descriptor.

    AcquireReadLease: Atomically resolves the payload snapshot and acquires a
    time-bounded read lease. The lease prevents the payload from being evicted
    or deleted until it expires or is explicitly released. Clients SHOULD call
    ReleaseLease when done to unblock pending spill or delete operations.

    ReleaseLease: Explicitly releases a lease before its expiry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveSnapshot = channel.unary_unary(
                '/payload.manager.services.v1.PayloadDataService/ResolveSnapshot',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotResponse.FromString,
                _registered_method=True)
        self.AcquireReadLease = channel.unary_unary(
                '/payload.manager.services.v1.PayloadDataService/AcquireReadLease',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/payload.manager.services.v1.PayloadDataService/ReleaseLease',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ReleaseLeaseRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PayloadDataServiceServicer(object):
    """
    High-frequency runtime data-plane operations.

    ResolveSnapshot: Returns the current placement descriptor for a payload
    (tier, location, state). This is an ADVISORY snapshot — the payload may
    move to a different tier or be deleted between this call and any subsequent
    read. Do NOT use this descriptor to access payload data directly. Use
    AcquireReadLease to obtain a stable, lease-protected descriptor.

    AcquireReadLease: Atomically resolves the payload snapshot and acquires a
    time-bounded read lease. The lease prevents the payload from being evicted
    or deleted until it expires or is explicitly released. Clients SHOULD call
    ReleaseLease when done to unblock pending spill or delete operations.

    ReleaseLease: Explicitly releases a lease before its expiry.
    """

    def ResolveSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireReadLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayloadDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSnapshot,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotResponse.SerializeToString,
            ),
            'AcquireReadLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireReadLease,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseResponse.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ReleaseLeaseRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payload.manager.services.v1.PayloadDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payload.manager.services.v1.PayloadDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayloadDataService(object):
    """
    High-frequency runtime data-plane operations.

    ResolveSnapshot: Returns the current placement descriptor for a payload
    (tier, location, state). This is an ADVISORY snapshot — the payload may
    move to a different tier or be deleted between this call and any subsequent
    read. Do NOT use this descriptor to access payload data directly. Use
    AcquireReadLease to obtain a stable, lease-protected descriptor.

    AcquireReadLease: Atomically resolves the payload snapshot and acquires a
    time-bounded read lease. The lease prevents the payload from being evicted
    or deleted until it expires or is explicitly released. Clients SHOULD call
    ReleaseLease when done to unblock pending spill or delete operations.

    ReleaseLease: Explicitly releases a lease before its expiry.
    """

    @staticmethod
    def ResolveSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadDataService/ResolveSnapshot',
            payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireReadLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadDataService/AcquireReadLease',
            payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadDataService/ReleaseLease',
            payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ReleaseLeaseRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
