# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import stream_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2


class PayloadStreamServiceStub(object):
  """Service-level contract:
  - CreateStream/DeleteStream manage stream lifecycle and retention state.
  - Append writes ordered records; Read and Subscribe consume records by offset.
  - Commit/GetCommitted persist and resolve consumer checkpoint positions.
  - GetRange materializes a stable range view for recording/snapshot use cases.
  For message-level semantics, ordering, and field guarantees, see
  payload/manager/runtime/v1/stream.proto.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateStream = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/CreateStream',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CreateStreamRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.DeleteStream = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/DeleteStream',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DeleteStreamRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Append = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/Append',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendResponse.FromString,
        )
    self.Read = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/Read',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/payload.manager.services.v1.PayloadStreamService/Subscribe',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeResponse.FromString,
        )
    self.Commit = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/Commit',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CommitRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetCommitted = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/GetCommitted',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedResponse.FromString,
        )
    self.GetRange = channel.unary_unary(
        '/payload.manager.services.v1.PayloadStreamService/GetRange',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeResponse.FromString,
        )


class PayloadStreamServiceServicer(object):
  """Service-level contract:
  - CreateStream/DeleteStream manage stream lifecycle and retention state.
  - Append writes ordered records; Read and Subscribe consume records by offset.
  - Commit/GetCommitted persist and resolve consumer checkpoint positions.
  - GetRange materializes a stable range view for recording/snapshot use cases.
  For message-level semantics, ordering, and field guarantees, see
  payload/manager/runtime/v1/stream.proto.
  """

  def CreateStream(self, request, context):
    """management
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Append(self, request, context):
    """producer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    """batch read
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    """live processing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Commit(self, request, context):
    """consumer checkpointing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCommitted(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRange(self, request, context):
    """recording snapshot
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PayloadStreamServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateStream': grpc.unary_unary_rpc_method_handler(
          servicer.CreateStream,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CreateStreamRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'DeleteStream': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteStream,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DeleteStreamRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Append': grpc.unary_unary_rpc_method_handler(
          servicer.Append,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendResponse.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeResponse.SerializeToString,
      ),
      'Commit': grpc.unary_unary_rpc_method_handler(
          servicer.Commit,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CommitRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetCommitted': grpc.unary_unary_rpc_method_handler(
          servicer.GetCommitted,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedResponse.SerializeToString,
      ),
      'GetRange': grpc.unary_unary_rpc_method_handler(
          servicer.GetRange,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payload.manager.services.v1.PayloadStreamService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
