# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/services/v1/payload_stream_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/services/v1/payload_stream_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import stream_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8payload/manager/services/v1/payload_stream_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\'payload/manager/runtime/v1/stream.proto2\xe7\t\n\x14PayloadStreamService\x12o\n\x0c\x43reateStream\x12/.payload.manager.runtime.v1.CreateStreamRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v1/streams:\x01*\x12\x8d\x01\n\x0c\x44\x65leteStream\x12/.payload.manager.runtime.v1.DeleteStreamRequest\x1a\x16.google.protobuf.Empty\"4\x82\xd3\xe4\x93\x02.*,/v1/streams/{stream.namespace}/{stream.name}\x12\xa0\x01\n\x06\x41ppend\x12).payload.manager.runtime.v1.AppendRequest\x1a*.payload.manager.runtime.v1.AppendResponse\"?\x82\xd3\xe4\x93\x02\x39\"4/v1/streams/{stream.namespace}/{stream.name}/entries:\x01*\x12\x97\x01\n\x04Read\x12\'.payload.manager.runtime.v1.ReadRequest\x1a(.payload.manager.runtime.v1.ReadResponse\"<\x82\xd3\xe4\x93\x02\x36\x12\x34/v1/streams/{stream.namespace}/{stream.name}/entries\x12\xaa\x01\n\tSubscribe\x12,.payload.manager.runtime.v1.SubscribeRequest\x1a-.payload.manager.runtime.v1.SubscribeResponse\">\x82\xd3\xe4\x93\x02\x38\x12\x36/v1/streams/{stream.namespace}/{stream.name}/subscribe0\x01\x12\x8b\x01\n\x06\x43ommit\x12).payload.manager.runtime.v1.CommitRequest\x1a\x16.google.protobuf.Empty\">\x82\xd3\xe4\x93\x02\x38\"3/v1/streams/{stream.namespace}/{stream.name}/commit:\x01*\x12\xb1\x01\n\x0cGetCommitted\x12/.payload.manager.runtime.v1.GetCommittedRequest\x1a\x30.payload.manager.runtime.v1.GetCommittedResponse\">\x82\xd3\xe4\x93\x02\x38\x12\x36/v1/streams/{stream.namespace}/{stream.name}/committed\x12\xa1\x01\n\x08GetRange\x12+.payload.manager.runtime.v1.GetRangeRequest\x1a,.payload.manager.runtime.v1.GetRangeResponse\":\x82\xd3\xe4\x93\x02\x34\x12\x32/v1/streams/{stream.namespace}/{stream.name}/rangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.services.v1.payload_stream_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['CreateStream']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['CreateStream']._serialized_options = b'\202\323\344\223\002\020\"\013/v1/streams:\001*'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['DeleteStream']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['DeleteStream']._serialized_options = b'\202\323\344\223\002.*,/v1/streams/{stream.namespace}/{stream.name}'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Append']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Append']._serialized_options = b'\202\323\344\223\0029\"4/v1/streams/{stream.namespace}/{stream.name}/entries:\001*'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Read']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Read']._serialized_options = b'\202\323\344\223\0026\0224/v1/streams/{stream.namespace}/{stream.name}/entries'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Subscribe']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Subscribe']._serialized_options = b'\202\323\344\223\0028\0226/v1/streams/{stream.namespace}/{stream.name}/subscribe'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Commit']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['Commit']._serialized_options = b'\202\323\344\223\0028\"3/v1/streams/{stream.namespace}/{stream.name}/commit:\001*'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['GetCommitted']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['GetCommitted']._serialized_options = b'\202\323\344\223\0028\0226/v1/streams/{stream.namespace}/{stream.name}/committed'
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['GetRange']._loaded_options = None
  _globals['_PAYLOADSTREAMSERVICE'].methods_by_name['GetRange']._serialized_options = b'\202\323\344\223\0024\0222/v1/streams/{stream.namespace}/{stream.name}/range'
  _globals['_PAYLOADSTREAMSERVICE']._serialized_start=190
  _globals['_PAYLOADSTREAMSERVICE']._serialized_end=1445
# @@protoc_insertion_point(module_scope)
