# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.catalog.v1 import catalog_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2
from payload.manager.catalog.v1 import lineage_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2
from payload.manager.runtime.v1 import lifecycle_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2
from payload.manager.runtime.v1 import tiering_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2


class PayloadCatalogServiceStub(object):
  """
  PayloadCatalogService

  This service manages durable state and semantic meaning of payloads.

  Responsibilities:
  - Allocate and commit payload lifecycle
  - Promotion and durability operations
  - Deletion
  - Metadata storage
  - Lineage tracking

  This is NOT the data plane.
  Workers should use PayloadDataService for reading bytes.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AllocatePayload = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/AllocatePayload',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadResponse.FromString,
        )
    self.CommitPayload = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/CommitPayload',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Delete',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Promote = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Promote',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteResponse.FromString,
        )
    self.Spill = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Spill',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillResponse.FromString,
        )
    self.Prefetch = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Prefetch',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PrefetchRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Pin = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Pin',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PinRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Unpin = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/Unpin',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.UnpinRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.AddLineage = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/AddLineage',
        request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.AddLineageRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetLineage = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/GetLineage',
        request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageResponse.FromString,
        )
    self.UpdatePayloadMetadata = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/UpdatePayloadMetadata',
        request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataResponse.FromString,
        )
    self.AppendPayloadMetadataEvent = channel.unary_unary(
        '/payload.manager.services.v1.PayloadCatalogService/AppendPayloadMetadataEvent',
        request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventResponse.FromString,
        )


class PayloadCatalogServiceServicer(object):
  """
  PayloadCatalogService

  This service manages durable state and semantic meaning of payloads.

  Responsibilities:
  - Allocate and commit payload lifecycle
  - Promotion and durability operations
  - Deletion
  - Metadata storage
  - Lineage tracking

  This is NOT the data plane.
  Workers should use PayloadDataService for reading bytes.

  """

  def AllocatePayload(self, request, context):
    """---------------------------------------------------------------------------
    Lifecycle
    ---------------------------------------------------------------------------


    Allocate reserves placement but the payload is invisible to readers
    until CommitPayload succeeds.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommitPayload(self, request, context):
    """
    Marks payload immutable and readable.
    After this point the payload must never change.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """
    Deletes payload placement and metadata.

    If force=true:
    - active leases are invalidated immediately
    - future reads must fail
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Promote(self, request, context):
    """---------------------------------------------------------------------------
    Tiering & Durability
    ---------------------------------------------------------------------------


    Requests movement to a higher tier (RAM/GPU/etc).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Spill(self, request, context):
    """
    Requests durable storage (usually disk/object storage).

    BLOCKING policy waits until durable or failure.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Prefetch(self, request, context):
    """
    Hint to move payload bytes to a faster tier.

    Best-effort and idempotent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pin(self, request, context):
    """
    Best-effort advisory that blocks spill while active.

    Pin duration is in milliseconds. duration_ms=0 means indefinite pin until Unpin.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unpin(self, request, context):
    """
    Removes an existing pin.

    Idempotent: unpinning an unpinned payload is a no-op.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddLineage(self, request, context):
    """---------------------------------------------------------------------------
    Lineage
    ---------------------------------------------------------------------------


    Records descriptive relationships between payloads.

    Does NOT enforce execution order.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLineage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePayloadMetadata(self, request, context):
    """---------------------------------------------------------------------------
    Metadata
    ---------------------------------------------------------------------------


    Updates current metadata view.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendPayloadMetadataEvent(self, request, context):
    """
    Appends immutable metadata history event.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PayloadCatalogServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AllocatePayload': grpc.unary_unary_rpc_method_handler(
          servicer.AllocatePayload,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadResponse.SerializeToString,
      ),
      'CommitPayload': grpc.unary_unary_rpc_method_handler(
          servicer.CommitPayload,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Promote': grpc.unary_unary_rpc_method_handler(
          servicer.Promote,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteResponse.SerializeToString,
      ),
      'Spill': grpc.unary_unary_rpc_method_handler(
          servicer.Spill,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillResponse.SerializeToString,
      ),
      'Prefetch': grpc.unary_unary_rpc_method_handler(
          servicer.Prefetch,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PrefetchRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Pin': grpc.unary_unary_rpc_method_handler(
          servicer.Pin,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PinRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Unpin': grpc.unary_unary_rpc_method_handler(
          servicer.Unpin,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.UnpinRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'AddLineage': grpc.unary_unary_rpc_method_handler(
          servicer.AddLineage,
          request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.AddLineageRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetLineage': grpc.unary_unary_rpc_method_handler(
          servicer.GetLineage,
          request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageRequest.FromString,
          response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageResponse.SerializeToString,
      ),
      'UpdatePayloadMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePayloadMetadata,
          request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataRequest.FromString,
          response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataResponse.SerializeToString,
      ),
      'AppendPayloadMetadataEvent': grpc.unary_unary_rpc_method_handler(
          servicer.AppendPayloadMetadataEvent,
          request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventRequest.FromString,
          response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payload.manager.services.v1.PayloadCatalogService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
