# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/services/v1/payload_ring_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/services/v1/payload_ring_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import ring_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_ring__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6payload/manager/services/v1/payload_ring_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a%payload/manager/runtime/v1/ring.proto2\x92\x06\n\x12PayloadRingService\x12\xa2\x01\n\x0f\x41\x63quireRingSlot\x12\x32.payload.manager.runtime.v1.AcquireRingSlotRequest\x1a\x33.payload.manager.runtime.v1.AcquireRingSlotResponse\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/rings/{ring_id}/acquire:\x01*\x12\x9e\x01\n\x0e\x43ommitRingSlot\x12\x31.payload.manager.runtime.v1.CommitRingSlotRequest\x1a\x32.payload.manager.runtime.v1.CommitRingSlotResponse\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/v1/rings/{ring_id}/commit:\x01*\x12\x83\x01\n\x07MapRing\x12*.payload.manager.runtime.v1.MapRingRequest\x1a+.payload.manager.runtime.v1.MapRingResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/rings/{ring_id}/map\x12\xab\x01\n\rLeaseRingSlot\x12\x30.payload.manager.runtime.v1.LeaseRingSlotRequest\x1a\x31.payload.manager.runtime.v1.LeaseRingSlotResponse\"5\x82\xd3\xe4\x93\x02/\"*/v1/rings/{ring_id}/slots/{slot_idx}/lease:\x01*\x12\x81\x01\n\x0fReleaseRingSlot\x12\x32.payload.manager.runtime.v1.ReleaseRingSlotRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/ring-leases/{lease_id}b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.services.v1.payload_ring_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['AcquireRingSlot']._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['AcquireRingSlot']._serialized_options = b'\202\323\344\223\002 \"\033/v1/rings/{ring_id}/acquire:\001*'
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['CommitRingSlot']._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['CommitRingSlot']._serialized_options = b'\202\323\344\223\002\037\"\032/v1/rings/{ring_id}/commit:\001*'
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['MapRing']._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['MapRing']._serialized_options = b'\202\323\344\223\002\031\022\027/v1/rings/{ring_id}/map'
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['LeaseRingSlot']._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['LeaseRingSlot']._serialized_options = b'\202\323\344\223\002/\"*/v1/rings/{ring_id}/slots/{slot_idx}/lease:\001*'
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['ReleaseRingSlot']._loaded_options = None
  _globals['_PAYLOADRINGSERVICE'].methods_by_name['ReleaseRingSlot']._serialized_options = b'\202\323\344\223\002\034*\032/v1/ring-leases/{lease_id}'
  _globals['_PAYLOADRINGSERVICE']._serialized_start=186
  _globals['_PAYLOADRINGSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
