# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/services/v1/payload_admin_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.admin.v1 import stats_pb2 as payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/services/v1/payload_admin_service.proto',
  package='payload.manager.services.v1',
  syntax='proto3',
  serialized_pb=_b('\n7payload/manager/services/v1/payload_admin_service.proto\x12\x1bpayload.manager.services.v1\x1a$payload/manager/admin/v1/stats.proto2o\n\x13PayloadAdminService\x12X\n\x05Stats\x12&.payload.manager.admin.v1.StatsRequest\x1a\'.payload.manager.admin.v1.StatsResponseb\x06proto3')
  ,
  dependencies=[payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOADADMINSERVICE = _descriptor.ServiceDescriptor(
  name='PayloadAdminService',
  full_name='payload.manager.services.v1.PayloadAdminService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=126,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='Stats',
    full_name='payload.manager.services.v1.PayloadAdminService.Stats',
    index=0,
    containing_service=None,
    input_type=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2._STATSREQUEST,
    output_type=payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2._STATSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYLOADADMINSERVICE)

DESCRIPTOR.services_by_name['PayloadAdminService'] = _PAYLOADADMINSERVICE

# @@protoc_insertion_point(module_scope)
