# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/services/v1/payload_data_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import lease_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/services/v1/payload_data_service.proto',
  package='payload.manager.services.v1',
  syntax='proto3',
  serialized_pb=_b('\n6payload/manager/services/v1/payload_data_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a&payload/manager/runtime/v1/lease.proto2\xe8\x02\n\x12PayloadDataService\x12z\n\x0fResolveSnapshot\x12\x32.payload.manager.runtime.v1.ResolveSnapshotRequest\x1a\x33.payload.manager.runtime.v1.ResolveSnapshotResponse\x12}\n\x10\x41\x63quireReadLease\x12\x33.payload.manager.runtime.v1.AcquireReadLeaseRequest\x1a\x34.payload.manager.runtime.v1.AcquireReadLeaseResponse\x12W\n\x0cReleaseLease\x12/.payload.manager.runtime.v1.ReleaseLeaseRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOADDATASERVICE = _descriptor.ServiceDescriptor(
  name='PayloadDataService',
  full_name='payload.manager.services.v1.PayloadDataService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=157,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='ResolveSnapshot',
    full_name='payload.manager.services.v1.PayloadDataService.ResolveSnapshot',
    index=0,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2._RESOLVESNAPSHOTREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2._RESOLVESNAPSHOTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AcquireReadLease',
    full_name='payload.manager.services.v1.PayloadDataService.AcquireReadLease',
    index=1,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2._ACQUIREREADLEASEREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2._ACQUIREREADLEASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReleaseLease',
    full_name='payload.manager.services.v1.PayloadDataService.ReleaseLease',
    index=2,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2._RELEASELEASEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYLOADDATASERVICE)

DESCRIPTOR.services_by_name['PayloadDataService'] = _PAYLOADDATASERVICE

# @@protoc_insertion_point(module_scope)
