# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/services/v1/payload_admin_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/services/v1/payload_admin_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from payload.manager.admin.v1 import stats_pb2 as payload_dot_manager_dot_admin_dot_v1_dot_stats__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7payload/manager/services/v1/payload_admin_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1cgoogle/api/annotations.proto\x1a$payload/manager/admin/v1/stats.proto2\x88\x01\n\x13PayloadAdminService\x12q\n\x05Stats\x12&.payload.manager.admin.v1.StatsRequest\x1a\'.payload.manager.admin.v1.StatsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admin/statsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.services.v1.payload_admin_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADADMINSERVICE'].methods_by_name['Stats']._loaded_options = None
  _globals['_PAYLOADADMINSERVICE'].methods_by_name['Stats']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/admin/stats'
  _globals['_PAYLOADADMINSERVICE']._serialized_start=157
  _globals['_PAYLOADADMINSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
