# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import lease_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2


class PayloadDataServiceStub(object):
  """
  High-frequency runtime operations.

  ResolveSnapshot → advisory
  AcquireReadLease → safe descriptor
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ResolveSnapshot = channel.unary_unary(
        '/payload.manager.services.v1.PayloadDataService/ResolveSnapshot',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotResponse.FromString,
        )
    self.AcquireReadLease = channel.unary_unary(
        '/payload.manager.services.v1.PayloadDataService/AcquireReadLease',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseRequest.SerializeToString,
        response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseResponse.FromString,
        )
    self.ReleaseLease = channel.unary_unary(
        '/payload.manager.services.v1.PayloadDataService/ReleaseLease',
        request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ReleaseLeaseRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class PayloadDataServiceServicer(object):
  """
  High-frequency runtime operations.

  ResolveSnapshot → advisory
  AcquireReadLease → safe descriptor
  """

  def ResolveSnapshot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AcquireReadLease(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReleaseLease(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PayloadDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ResolveSnapshot': grpc.unary_unary_rpc_method_handler(
          servicer.ResolveSnapshot,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ResolveSnapshotResponse.SerializeToString,
      ),
      'AcquireReadLease': grpc.unary_unary_rpc_method_handler(
          servicer.AcquireReadLease,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseRequest.FromString,
          response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.AcquireReadLeaseResponse.SerializeToString,
      ),
      'ReleaseLease': grpc.unary_unary_rpc_method_handler(
          servicer.ReleaseLease,
          request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2.ReleaseLeaseRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payload.manager.services.v1.PayloadDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
