# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import stream_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payload/manager/services/v1/payload_stream_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayloadStreamServiceStub(object):
    """Service-level contract:
    - CreateStream/DeleteStream manage stream lifecycle and retention state.
    - Append writes ordered records; Read and Subscribe consume records by offset.
    - Commit/GetCommitted persist and resolve consumer checkpoint positions.
    - GetRange materializes a stable range view for recording/snapshot use cases.
    For message-level semantics, ordering, and field guarantees, see
    payload/manager/runtime/v1/stream.proto.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStream = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/CreateStream',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CreateStreamRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteStream = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/DeleteStream',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DeleteStreamRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Append = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/Append',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/Read',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/payload.manager.services.v1.PayloadStreamService/Subscribe',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/Commit',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CommitRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCommitted = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/GetCommitted',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedResponse.FromString,
                _registered_method=True)
        self.GetRange = channel.unary_unary(
                '/payload.manager.services.v1.PayloadStreamService/GetRange',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeResponse.FromString,
                _registered_method=True)


class PayloadStreamServiceServicer(object):
    """Service-level contract:
    - CreateStream/DeleteStream manage stream lifecycle and retention state.
    - Append writes ordered records; Read and Subscribe consume records by offset.
    - Commit/GetCommitted persist and resolve consumer checkpoint positions.
    - GetRange materializes a stable range view for recording/snapshot use cases.
    For message-level semantics, ordering, and field guarantees, see
    payload/manager/runtime/v1/stream.proto.
    """

    def CreateStream(self, request, context):
        """management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Append(self, request, context):
        """producer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """batch read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """live processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """consumer checkpointing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommitted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRange(self, request, context):
        """recording snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayloadStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStream,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CreateStreamRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteStream': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStream,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DeleteStreamRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CommitRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCommitted': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommitted,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedResponse.SerializeToString,
            ),
            'GetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payload.manager.services.v1.PayloadStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payload.manager.services.v1.PayloadStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayloadStreamService(object):
    """Service-level contract:
    - CreateStream/DeleteStream manage stream lifecycle and retention state.
    - Append writes ordered records; Read and Subscribe consume records by offset.
    - Commit/GetCommitted persist and resolve consumer checkpoint positions.
    - GetRange materializes a stable range view for recording/snapshot use cases.
    For message-level semantics, ordering, and field guarantees, see
    payload/manager/runtime/v1/stream.proto.
    """

    @staticmethod
    def CreateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/CreateStream',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CreateStreamRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/DeleteStream',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DeleteStreamRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/Append',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/Read',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/Subscribe',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/Commit',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.CommitRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommitted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/GetCommitted',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetCommittedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadStreamService/GetRange',
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.GetRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
