# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/services/v1/payload_data_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/services/v1/payload_data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import lease_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lease__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6payload/manager/services/v1/payload_data_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a&payload/manager/runtime/v1/lease.proto2\xe3\x03\n\x12PayloadDataService\x12\xa4\x01\n\x0fResolveSnapshot\x12\x32.payload.manager.runtime.v1.ResolveSnapshotRequest\x1a\x33.payload.manager.runtime.v1.ResolveSnapshotResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/payloads/{id.value}/snapshot\x12\xa7\x01\n\x10\x41\x63quireReadLease\x12\x33.payload.manager.runtime.v1.AcquireReadLeaseRequest\x1a\x34.payload.manager.runtime.v1.AcquireReadLeaseResponse\"(\x82\xd3\xe4\x93\x02\"\"\x1d/v1/payloads/{id.value}/lease:\x01*\x12|\n\x0cReleaseLease\x12/.payload.manager.runtime.v1.ReleaseLeaseRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/leases/{lease_id.value}b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.services.v1.payload_data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADDATASERVICE'].methods_by_name['ResolveSnapshot']._loaded_options = None
  _globals['_PAYLOADDATASERVICE'].methods_by_name['ResolveSnapshot']._serialized_options = b'\202\323\344\223\002\"\022 /v1/payloads/{id.value}/snapshot'
  _globals['_PAYLOADDATASERVICE'].methods_by_name['AcquireReadLease']._loaded_options = None
  _globals['_PAYLOADDATASERVICE'].methods_by_name['AcquireReadLease']._serialized_options = b'\202\323\344\223\002\"\"\035/v1/payloads/{id.value}/lease:\001*'
  _globals['_PAYLOADDATASERVICE'].methods_by_name['ReleaseLease']._loaded_options = None
  _globals['_PAYLOADDATASERVICE'].methods_by_name['ReleaseLease']._serialized_options = b'\202\323\344\223\002\035*\033/v1/leases/{lease_id.value}'
  _globals['_PAYLOADDATASERVICE']._serialized_start=187
  _globals['_PAYLOADDATASERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
