# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.catalog.v1 import catalog_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2
from payload.manager.catalog.v1 import lineage_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2
from payload.manager.runtime.v1 import lifecycle_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2
from payload.manager.runtime.v1 import tiering_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payload/manager/services/v1/payload_catalog_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayloadCatalogServiceStub(object):
    """
    PayloadCatalogService

    This service manages durable state and semantic meaning of payloads.

    Responsibilities:
    - Allocate and commit payload lifecycle
    - Promotion and durability operations
    - Deletion
    - Metadata storage
    - Lineage tracking

    This is NOT the data plane.
    Workers should use PayloadDataService for reading bytes.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocatePayload = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/AllocatePayload',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadResponse.FromString,
                _registered_method=True)
        self.CommitPayload = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/CommitPayload',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Delete',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Promote = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Promote',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteResponse.FromString,
                _registered_method=True)
        self.Spill = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Spill',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillResponse.FromString,
                _registered_method=True)
        self.Prefetch = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Prefetch',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PrefetchRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Pin = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Pin',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PinRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Unpin = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/Unpin',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.UnpinRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddLineage = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/AddLineage',
                request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.AddLineageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLineage = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/GetLineage',
                request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageResponse.FromString,
                _registered_method=True)
        self.UpdatePayloadMetadata = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/UpdatePayloadMetadata',
                request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataResponse.FromString,
                _registered_method=True)
        self.AppendPayloadMetadataEvent = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/AppendPayloadMetadataEvent',
                request_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventResponse.FromString,
                _registered_method=True)
        self.ListPayloads = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/ListPayloads',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsResponse.FromString,
                _registered_method=True)
        self.ImportPayload = channel.unary_unary(
                '/payload.manager.services.v1.PayloadCatalogService/ImportPayload',
                request_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadRequest.SerializeToString,
                response_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadResponse.FromString,
                _registered_method=True)


class PayloadCatalogServiceServicer(object):
    """
    PayloadCatalogService

    This service manages durable state and semantic meaning of payloads.

    Responsibilities:
    - Allocate and commit payload lifecycle
    - Promotion and durability operations
    - Deletion
    - Metadata storage
    - Lineage tracking

    This is NOT the data plane.
    Workers should use PayloadDataService for reading bytes.

    """

    def AllocatePayload(self, request, context):
        """---------------------------------------------------------------------------
        Lifecycle
        ---------------------------------------------------------------------------


        Allocate reserves placement but the payload is invisible to readers
        until CommitPayload succeeds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitPayload(self, request, context):
        """
        Marks payload immutable and readable.
        After this point the payload must never change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """
        Deletes payload placement and metadata.

        If force=true:
        - active leases are invalidated immediately
        - future reads must fail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Promote(self, request, context):
        """---------------------------------------------------------------------------
        Tiering & Durability
        ---------------------------------------------------------------------------


        Requests movement to a higher tier (RAM/GPU/etc).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Spill(self, request, context):
        """
        Requests durable storage (usually disk/object storage).

        BLOCKING policy waits until durable or failure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prefetch(self, request, context):
        """
        Hint to move payload bytes to a faster tier.

        Best-effort and idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pin(self, request, context):
        """
        Best-effort advisory that blocks spill while active.

        Pin duration is in milliseconds. duration_ms=0 means indefinite pin until Unpin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unpin(self, request, context):
        """
        Removes an existing pin.

        Idempotent: unpinning an unpinned payload is a no-op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLineage(self, request, context):
        """---------------------------------------------------------------------------
        Lineage
        ---------------------------------------------------------------------------


        Records descriptive relationships between payloads.

        Does NOT enforce execution order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLineage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePayloadMetadata(self, request, context):
        """---------------------------------------------------------------------------
        Metadata
        ---------------------------------------------------------------------------


        Updates current metadata view.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendPayloadMetadataEvent(self, request, context):
        """
        Appends immutable metadata history event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPayloads(self, request, context):
        """---------------------------------------------------------------------------
        Listing
        ---------------------------------------------------------------------------


        Returns a summary row for every payload known to the service.
        Optionally filtered by tier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportPayload(self, request, context):
        """---------------------------------------------------------------------------
        Object-tier client upload
        ---------------------------------------------------------------------------


        Register an externally-uploaded object-tier payload as DURABLE.

        The client:
        1. Calls AllocatePayload with preferred_tier=TIER_OBJECT and receives
        object_upload_path in the response.
        2. Uploads payload bytes directly to object_upload_path via Arrow
        filesystem (no bytes transit gRPC).
        3. Calls ImportPayload to hand ownership to the manager.

        The manager writes the sidecar metadata and transitions the payload
        to PAYLOAD_STATE_DURABLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayloadCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocatePayload': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocatePayload,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadResponse.SerializeToString,
            ),
            'CommitPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitPayload,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Promote': grpc.unary_unary_rpc_method_handler(
                    servicer.Promote,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteResponse.SerializeToString,
            ),
            'Spill': grpc.unary_unary_rpc_method_handler(
                    servicer.Spill,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillResponse.SerializeToString,
            ),
            'Prefetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefetch,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PrefetchRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Pin': grpc.unary_unary_rpc_method_handler(
                    servicer.Pin,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PinRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Unpin': grpc.unary_unary_rpc_method_handler(
                    servicer.Unpin,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.UnpinRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddLineage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLineage,
                    request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.AddLineageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetLineage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLineage,
                    request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageRequest.FromString,
                    response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageResponse.SerializeToString,
            ),
            'UpdatePayloadMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePayloadMetadata,
                    request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataRequest.FromString,
                    response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataResponse.SerializeToString,
            ),
            'AppendPayloadMetadataEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendPayloadMetadataEvent,
                    request_deserializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventRequest.FromString,
                    response_serializer=payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventResponse.SerializeToString,
            ),
            'ListPayloads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPayloads,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsResponse.SerializeToString,
            ),
            'ImportPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportPayload,
                    request_deserializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadRequest.FromString,
                    response_serializer=payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payload.manager.services.v1.PayloadCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payload.manager.services.v1.PayloadCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayloadCatalogService(object):
    """
    PayloadCatalogService

    This service manages durable state and semantic meaning of payloads.

    Responsibilities:
    - Allocate and commit payload lifecycle
    - Promotion and durability operations
    - Deletion
    - Metadata storage
    - Lineage tracking

    This is NOT the data plane.
    Workers should use PayloadDataService for reading bytes.

    """

    @staticmethod
    def AllocatePayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/AllocatePayload',
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.AllocatePayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/CommitPayload',
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.CommitPayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Delete',
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Promote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Promote',
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PromoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Spill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Spill',
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.SpillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prefetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Prefetch',
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PrefetchRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Pin',
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.PinRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unpin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/Unpin',
            payload_dot_manager_dot_runtime_dot_v1_dot_tiering__pb2.UnpinRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLineage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/AddLineage',
            payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.AddLineageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLineage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/GetLineage',
            payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageRequest.SerializeToString,
            payload_dot_manager_dot_catalog_dot_v1_dot_lineage__pb2.GetLineageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePayloadMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/UpdatePayloadMetadata',
            payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataRequest.SerializeToString,
            payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.UpdatePayloadMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendPayloadMetadataEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/AppendPayloadMetadataEvent',
            payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventRequest.SerializeToString,
            payload_dot_manager_dot_catalog_dot_v1_dot_catalog__pb2.AppendPayloadMetadataEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPayloads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/ListPayloads',
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ListPayloadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payload.manager.services.v1.PayloadCatalogService/ImportPayload',
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadRequest.SerializeToString,
            payload_dot_manager_dot_runtime_dot_v1_dot_lifecycle__pb2.ImportPayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
