# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/services/v1/payload_stream_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payload.manager.runtime.v1 import stream_pb2 as payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/services/v1/payload_stream_service.proto',
  package='payload.manager.services.v1',
  syntax='proto3',
  serialized_pb=_b('\n8payload/manager/services/v1/payload_stream_service.proto\x12\x1bpayload.manager.services.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\'payload/manager/runtime/v1/stream.proto2\x97\x06\n\x14PayloadStreamService\x12W\n\x0c\x43reateStream\x12/.payload.manager.runtime.v1.CreateStreamRequest\x1a\x16.google.protobuf.Empty\x12W\n\x0c\x44\x65leteStream\x12/.payload.manager.runtime.v1.DeleteStreamRequest\x1a\x16.google.protobuf.Empty\x12_\n\x06\x41ppend\x12).payload.manager.runtime.v1.AppendRequest\x1a*.payload.manager.runtime.v1.AppendResponse\x12Y\n\x04Read\x12\'.payload.manager.runtime.v1.ReadRequest\x1a(.payload.manager.runtime.v1.ReadResponse\x12j\n\tSubscribe\x12,.payload.manager.runtime.v1.SubscribeRequest\x1a-.payload.manager.runtime.v1.SubscribeResponse0\x01\x12K\n\x06\x43ommit\x12).payload.manager.runtime.v1.CommitRequest\x1a\x16.google.protobuf.Empty\x12q\n\x0cGetCommitted\x12/.payload.manager.runtime.v1.GetCommittedRequest\x1a\x30.payload.manager.runtime.v1.GetCommittedResponse\x12\x65\n\x08GetRange\x12+.payload.manager.runtime.v1.GetRangeRequest\x1a,.payload.manager.runtime.v1.GetRangeResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOADSTREAMSERVICE = _descriptor.ServiceDescriptor(
  name='PayloadStreamService',
  full_name='payload.manager.services.v1.PayloadStreamService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=160,
  serialized_end=951,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateStream',
    full_name='payload.manager.services.v1.PayloadStreamService.CreateStream',
    index=0,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._CREATESTREAMREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStream',
    full_name='payload.manager.services.v1.PayloadStreamService.DeleteStream',
    index=1,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._DELETESTREAMREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Append',
    full_name='payload.manager.services.v1.PayloadStreamService.Append',
    index=2,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._APPENDREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._APPENDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='payload.manager.services.v1.PayloadStreamService.Read',
    index=3,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._READREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._READRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='payload.manager.services.v1.PayloadStreamService.Subscribe',
    index=4,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._SUBSCRIBEREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._SUBSCRIBERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Commit',
    full_name='payload.manager.services.v1.PayloadStreamService.Commit',
    index=5,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._COMMITREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCommitted',
    full_name='payload.manager.services.v1.PayloadStreamService.GetCommitted',
    index=6,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._GETCOMMITTEDREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._GETCOMMITTEDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRange',
    full_name='payload.manager.services.v1.PayloadStreamService.GetRange',
    index=7,
    containing_service=None,
    input_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._GETRANGEREQUEST,
    output_type=payload_dot_manager_dot_runtime_dot_v1_dot_stream__pb2._GETRANGERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYLOADSTREAMSERVICE)

DESCRIPTOR.services_by_name['PayloadStreamService'] = _PAYLOADSTREAMSERVICE

# @@protoc_insertion_point(module_scope)
