services:
  payload-manager:
    build:
      context: .
      dockerfile: Dockerfile.otel
    restart: unless-stopped
    hostname: payload-manager
    command: ["./payload-manager", "--config", "/app/conf/runtime-docker-sqlite.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/50051'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    ipc: host
    ports:
      - "50054:50051"
    volumes:
      - ./config/runtime-docker-sqlite.yaml:/app/conf/runtime-docker-sqlite.yaml:ro
      - payload-otel-sqlite-data:/var/lib/payload-manager

volumes:
  payload-otel-sqlite-data:
