services:
  payload-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    hostname: payload-manager
    command: ["./payload-manager", "--config", "/app/conf/runtime-docker-no-otel-sqlite.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/50051'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    ipc: host
    ports:
      - "50052:50051"
    volumes:
      - ../config/runtime-docker-no-otel-sqlite.yaml:/app/conf/runtime-docker-no-otel-sqlite.yaml:ro
      - payload-sqlite-data:/var/lib/payload-manager

volumes:
  payload-sqlite-data:
