# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/catalog/v1/catalog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2
from payload.manager.catalog.v1 import metadata_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/catalog/v1/catalog.proto',
  package='payload.manager.catalog.v1',
  syntax='proto3',
  serialized_pb=_b('\n(payload/manager/catalog/v1/catalog.proto\x12\x1apayload.manager.catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a payload/manager/core/v1/id.proto\x1a)payload/manager/catalog/v1/metadata.proto\x1a$payload/manager/core/v1/policy.proto\"\xe7\x01\n\x1cUpdatePayloadMetadataRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x39\n\x04mode\x18\x02 \x01(\x0e\x32+.payload.manager.core.v1.MetadataUpdateMode\x12=\n\x08metadata\x18\x03 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12\r\n\x05\x61\x63tor\x18\x04 \x01(\t\x12\x0e\n\x06reason\x18\x05 \x01(\t\"\xbe\x01\n\x1dUpdatePayloadMetadataResponse\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12=\n\x08metadata\x18\x02 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb3\x01\n!AppendPayloadMetadataEventRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12=\n\x08metadata\x18\x02 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"\x84\x01\n\"AppendPayloadMetadataEventResponse\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12.\n\nevent_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_policy__pb2.DESCRIPTOR,])




_UPDATEPAYLOADMETADATAREQUEST = _descriptor.Descriptor(
  name='UpdatePayloadMetadataRequest',
  full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actor', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest.actor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataRequest.reason', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=452,
)


_UPDATEPAYLOADMETADATARESPONSE = _descriptor.Descriptor(
  name='UpdatePayloadMetadataResponse',
  full_name='payload.manager.catalog.v1.UpdatePayloadMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataResponse.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='payload.manager.catalog.v1.UpdatePayloadMetadataResponse.updated_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=645,
)


_APPENDPAYLOADMETADATAEVENTREQUEST = _descriptor.Descriptor(
  name='AppendPayloadMetadataEventRequest',
  full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventRequest.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventRequest.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventRequest.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=827,
)


_APPENDPAYLOADMETADATAEVENTRESPONSE = _descriptor.Descriptor(
  name='AppendPayloadMetadataEventResponse',
  full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventResponse.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_time', full_name='payload.manager.catalog.v1.AppendPayloadMetadataEventResponse.event_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=962,
)

_UPDATEPAYLOADMETADATAREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_UPDATEPAYLOADMETADATAREQUEST.fields_by_name['mode'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._METADATAUPDATEMODE
_UPDATEPAYLOADMETADATAREQUEST.fields_by_name['metadata'].message_type = payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2._PAYLOADMETADATA
_UPDATEPAYLOADMETADATARESPONSE.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_UPDATEPAYLOADMETADATARESPONSE.fields_by_name['metadata'].message_type = payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2._PAYLOADMETADATA
_UPDATEPAYLOADMETADATARESPONSE.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_APPENDPAYLOADMETADATAEVENTREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_APPENDPAYLOADMETADATAEVENTREQUEST.fields_by_name['metadata'].message_type = payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2._PAYLOADMETADATA
_APPENDPAYLOADMETADATAEVENTRESPONSE.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_APPENDPAYLOADMETADATAEVENTRESPONSE.fields_by_name['event_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UpdatePayloadMetadataRequest'] = _UPDATEPAYLOADMETADATAREQUEST
DESCRIPTOR.message_types_by_name['UpdatePayloadMetadataResponse'] = _UPDATEPAYLOADMETADATARESPONSE
DESCRIPTOR.message_types_by_name['AppendPayloadMetadataEventRequest'] = _APPENDPAYLOADMETADATAEVENTREQUEST
DESCRIPTOR.message_types_by_name['AppendPayloadMetadataEventResponse'] = _APPENDPAYLOADMETADATAEVENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdatePayloadMetadataRequest = _reflection.GeneratedProtocolMessageType('UpdatePayloadMetadataRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEPAYLOADMETADATAREQUEST,
  __module__ = 'payload.manager.catalog.v1.catalog_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.UpdatePayloadMetadataRequest)
  ))
_sym_db.RegisterMessage(UpdatePayloadMetadataRequest)

UpdatePayloadMetadataResponse = _reflection.GeneratedProtocolMessageType('UpdatePayloadMetadataResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEPAYLOADMETADATARESPONSE,
  __module__ = 'payload.manager.catalog.v1.catalog_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.UpdatePayloadMetadataResponse)
  ))
_sym_db.RegisterMessage(UpdatePayloadMetadataResponse)

AppendPayloadMetadataEventRequest = _reflection.GeneratedProtocolMessageType('AppendPayloadMetadataEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _APPENDPAYLOADMETADATAEVENTREQUEST,
  __module__ = 'payload.manager.catalog.v1.catalog_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.AppendPayloadMetadataEventRequest)
  ))
_sym_db.RegisterMessage(AppendPayloadMetadataEventRequest)

AppendPayloadMetadataEventResponse = _reflection.GeneratedProtocolMessageType('AppendPayloadMetadataEventResponse', (_message.Message,), dict(
  DESCRIPTOR = _APPENDPAYLOADMETADATAEVENTRESPONSE,
  __module__ = 'payload.manager.catalog.v1.catalog_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.AppendPayloadMetadataEventResponse)
  ))
_sym_db.RegisterMessage(AppendPayloadMetadataEventResponse)


# @@protoc_insertion_point(module_scope)
