# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/catalog/v1/catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/catalog/v1/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2
from payload.manager.catalog.v1 import metadata_pb2 as payload_dot_manager_dot_catalog_dot_v1_dot_metadata__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(payload/manager/catalog/v1/catalog.proto\x12\x1apayload.manager.catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a payload/manager/core/v1/id.proto\x1a)payload/manager/catalog/v1/metadata.proto\x1a$payload/manager/core/v1/policy.proto\"\xe7\x01\n\x1cUpdatePayloadMetadataRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x39\n\x04mode\x18\x02 \x01(\x0e\x32+.payload.manager.core.v1.MetadataUpdateMode\x12=\n\x08metadata\x18\x03 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12\r\n\x05\x61\x63tor\x18\x04 \x01(\t\x12\x0e\n\x06reason\x18\x05 \x01(\t\"\xbe\x01\n\x1dUpdatePayloadMetadataResponse\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12=\n\x08metadata\x18\x02 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb3\x01\n!AppendPayloadMetadataEventRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12=\n\x08metadata\x18\x02 \x01(\x0b\x32+.payload.manager.catalog.v1.PayloadMetadata\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"\x84\x01\n\"AppendPayloadMetadataEventResponse\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12.\n\nevent_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.catalog.v1.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEPAYLOADMETADATAREQUEST']._serialized_start=221
  _globals['_UPDATEPAYLOADMETADATAREQUEST']._serialized_end=452
  _globals['_UPDATEPAYLOADMETADATARESPONSE']._serialized_start=455
  _globals['_UPDATEPAYLOADMETADATARESPONSE']._serialized_end=645
  _globals['_APPENDPAYLOADMETADATAEVENTREQUEST']._serialized_start=648
  _globals['_APPENDPAYLOADMETADATAEVENTREQUEST']._serialized_end=827
  _globals['_APPENDPAYLOADMETADATAEVENTRESPONSE']._serialized_start=830
  _globals['_APPENDPAYLOADMETADATAEVENTRESPONSE']._serialized_end=962
# @@protoc_insertion_point(module_scope)
