# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/catalog/v1/lineage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/catalog/v1/lineage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(payload/manager/catalog/v1/lineage.proto\x12\x1apayload.manager.catalog.v1\x1a payload/manager/core/v1/id.proto\"v\n\x0bLineageEdge\x12\x32\n\x06parent\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\x0c\"\x80\x01\n\x11\x41\x64\x64LineageRequest\x12\x31\n\x05\x63hild\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x38\n\x07parents\x18\x02 \x03(\x0b\x32\'.payload.manager.catalog.v1.LineageEdge\"h\n\x11GetLineageRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x10\n\x08upstream\x18\x02 \x01(\x08\x12\x11\n\tmax_depth\x18\x03 \x01(\r\"L\n\x12GetLineageResponse\x12\x36\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\'.payload.manager.catalog.v1.LineageEdgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.catalog.v1.lineage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEAGEEDGE']._serialized_start=106
  _globals['_LINEAGEEDGE']._serialized_end=224
  _globals['_ADDLINEAGEREQUEST']._serialized_start=227
  _globals['_ADDLINEAGEREQUEST']._serialized_end=355
  _globals['_GETLINEAGEREQUEST']._serialized_start=357
  _globals['_GETLINEAGEREQUEST']._serialized_end=461
  _globals['_GETLINEAGERESPONSE']._serialized_start=463
  _globals['_GETLINEAGERESPONSE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
