# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/catalog/v1/lineage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/catalog/v1/lineage.proto',
  package='payload.manager.catalog.v1',
  syntax='proto3',
  serialized_pb=_b('\n(payload/manager/catalog/v1/lineage.proto\x12\x1apayload.manager.catalog.v1\x1a payload/manager/core/v1/id.proto\"v\n\x0bLineageEdge\x12\x32\n\x06parent\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x12\n\nparameters\x18\x04 \x01(\x0c\"\x80\x01\n\x11\x41\x64\x64LineageRequest\x12\x31\n\x05\x63hild\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x38\n\x07parents\x18\x02 \x03(\x0b\x32\'.payload.manager.catalog.v1.LineageEdge\"h\n\x11GetLineageRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x10\n\x08upstream\x18\x02 \x01(\x08\x12\x11\n\tmax_depth\x18\x03 \x01(\r\"L\n\x12GetLineageResponse\x12\x36\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\'.payload.manager.catalog.v1.LineageEdgeb\x06proto3')
  ,
  dependencies=[payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,])




_LINEAGEEDGE = _descriptor.Descriptor(
  name='LineageEdge',
  full_name='payload.manager.catalog.v1.LineageEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='payload.manager.catalog.v1.LineageEdge.parent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='payload.manager.catalog.v1.LineageEdge.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='payload.manager.catalog.v1.LineageEdge.role', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='payload.manager.catalog.v1.LineageEdge.parameters', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=224,
)


_ADDLINEAGEREQUEST = _descriptor.Descriptor(
  name='AddLineageRequest',
  full_name='payload.manager.catalog.v1.AddLineageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='child', full_name='payload.manager.catalog.v1.AddLineageRequest.child', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parents', full_name='payload.manager.catalog.v1.AddLineageRequest.parents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=355,
)


_GETLINEAGEREQUEST = _descriptor.Descriptor(
  name='GetLineageRequest',
  full_name='payload.manager.catalog.v1.GetLineageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.GetLineageRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upstream', full_name='payload.manager.catalog.v1.GetLineageRequest.upstream', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_depth', full_name='payload.manager.catalog.v1.GetLineageRequest.max_depth', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=461,
)


_GETLINEAGERESPONSE = _descriptor.Descriptor(
  name='GetLineageResponse',
  full_name='payload.manager.catalog.v1.GetLineageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edges', full_name='payload.manager.catalog.v1.GetLineageResponse.edges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=539,
)

_LINEAGEEDGE.fields_by_name['parent'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_ADDLINEAGEREQUEST.fields_by_name['child'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_ADDLINEAGEREQUEST.fields_by_name['parents'].message_type = _LINEAGEEDGE
_GETLINEAGEREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_GETLINEAGERESPONSE.fields_by_name['edges'].message_type = _LINEAGEEDGE
DESCRIPTOR.message_types_by_name['LineageEdge'] = _LINEAGEEDGE
DESCRIPTOR.message_types_by_name['AddLineageRequest'] = _ADDLINEAGEREQUEST
DESCRIPTOR.message_types_by_name['GetLineageRequest'] = _GETLINEAGEREQUEST
DESCRIPTOR.message_types_by_name['GetLineageResponse'] = _GETLINEAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineageEdge = _reflection.GeneratedProtocolMessageType('LineageEdge', (_message.Message,), dict(
  DESCRIPTOR = _LINEAGEEDGE,
  __module__ = 'payload.manager.catalog.v1.lineage_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.LineageEdge)
  ))
_sym_db.RegisterMessage(LineageEdge)

AddLineageRequest = _reflection.GeneratedProtocolMessageType('AddLineageRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDLINEAGEREQUEST,
  __module__ = 'payload.manager.catalog.v1.lineage_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.AddLineageRequest)
  ))
_sym_db.RegisterMessage(AddLineageRequest)

GetLineageRequest = _reflection.GeneratedProtocolMessageType('GetLineageRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETLINEAGEREQUEST,
  __module__ = 'payload.manager.catalog.v1.lineage_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.GetLineageRequest)
  ))
_sym_db.RegisterMessage(GetLineageRequest)

GetLineageResponse = _reflection.GeneratedProtocolMessageType('GetLineageResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETLINEAGERESPONSE,
  __module__ = 'payload.manager.catalog.v1.lineage_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.GetLineageResponse)
  ))
_sym_db.RegisterMessage(GetLineageResponse)


# @@protoc_insertion_point(module_scope)
