# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/catalog/v1/metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/catalog/v1/metadata.proto',
  package='payload.manager.catalog.v1',
  syntax='proto3',
  serialized_pb=_b('\n)payload/manager/catalog/v1/metadata.proto\x12\x1apayload.manager.catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a payload/manager/core/v1/id.proto\"_\n\x0fPayloadMetadata\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06schema\x18\x03 \x01(\t\"\x9d\x01\n\x14PayloadMetadataEvent\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,])




_PAYLOADMETADATA = _descriptor.Descriptor(
  name='PayloadMetadata',
  full_name='payload.manager.catalog.v1.PayloadMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.PayloadMetadata.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='payload.manager.catalog.v1.PayloadMetadata.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='payload.manager.catalog.v1.PayloadMetadata.schema', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=235,
)


_PAYLOADMETADATAEVENT = _descriptor.Descriptor(
  name='PayloadMetadataEvent',
  full_name='payload.manager.catalog.v1.PayloadMetadataEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.catalog.v1.PayloadMetadataEvent.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='payload.manager.catalog.v1.PayloadMetadataEvent.ts', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='payload.manager.catalog.v1.PayloadMetadataEvent.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='payload.manager.catalog.v1.PayloadMetadataEvent.source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='payload.manager.catalog.v1.PayloadMetadataEvent.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=395,
)

_PAYLOADMETADATA.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_PAYLOADMETADATAEVENT.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_PAYLOADMETADATAEVENT.fields_by_name['ts'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PayloadMetadata'] = _PAYLOADMETADATA
DESCRIPTOR.message_types_by_name['PayloadMetadataEvent'] = _PAYLOADMETADATAEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PayloadMetadata = _reflection.GeneratedProtocolMessageType('PayloadMetadata', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOADMETADATA,
  __module__ = 'payload.manager.catalog.v1.metadata_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.PayloadMetadata)
  ))
_sym_db.RegisterMessage(PayloadMetadata)

PayloadMetadataEvent = _reflection.GeneratedProtocolMessageType('PayloadMetadataEvent', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOADMETADATAEVENT,
  __module__ = 'payload.manager.catalog.v1.metadata_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.catalog.v1.PayloadMetadataEvent)
  ))
_sym_db.RegisterMessage(PayloadMetadataEvent)


# @@protoc_insertion_point(module_scope)
