# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/admin/v1/stats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/admin/v1/stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$payload/manager/admin/v1/stats.proto\x12\x18payload.manager.admin.v1\"\x0e\n\x0cStatsRequest\"\xc4\x01\n\tRingStats\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\x12\x13\n\x0bslots_total\x18\x02 \x01(\r\x12\x17\n\x0fslots_available\x18\x03 \x01(\r\x12\x15\n\rslots_writing\x18\x04 \x01(\r\x12\x14\n\x0cslots_leased\x18\x05 \x01(\r\x12\x15\n\rleases_active\x18\x06 \x01(\x04\x12\x17\n\x0fslots_reclaimed\x18\x07 \x01(\x04\x12\x1b\n\x13slot_capacity_bytes\x18\x08 \x01(\x04\"\xef\x01\n\rStatsResponse\x12\x14\n\x0cpayloads_gpu\x18\x01 \x01(\x04\x12\x14\n\x0cpayloads_ram\x18\x02 \x01(\x04\x12\x15\n\rpayloads_disk\x18\x03 \x01(\x04\x12\x17\n\x0fpayloads_object\x18\x07 \x01(\x04\x12\x11\n\tbytes_gpu\x18\x04 \x01(\x04\x12\x11\n\tbytes_ram\x18\x05 \x01(\x04\x12\x12\n\nbytes_disk\x18\x06 \x01(\x04\x12\x14\n\x0c\x62ytes_object\x18\x08 \x01(\x04\x12\x32\n\x05rings\x18\t \x03(\x0b\x32#.payload.manager.admin.v1.RingStatsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.admin.v1.stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSREQUEST']._serialized_start=66
  _globals['_STATSREQUEST']._serialized_end=80
  _globals['_RINGSTATS']._serialized_start=83
  _globals['_RINGSTATS']._serialized_end=279
  _globals['_STATSRESPONSE']._serialized_start=282
  _globals['_STATSRESPONSE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
