# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/admin/v1/stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/admin/v1/stats.proto',
  package='payload.manager.admin.v1',
  syntax='proto3',
  serialized_pb=_b('\n$payload/manager/admin/v1/stats.proto\x12\x18payload.manager.admin.v1\"\x0e\n\x0cStatsRequest\"\x8c\x01\n\rStatsResponse\x12\x14\n\x0cpayloads_gpu\x18\x01 \x01(\x04\x12\x14\n\x0cpayloads_ram\x18\x02 \x01(\x04\x12\x15\n\rpayloads_disk\x18\x03 \x01(\x04\x12\x11\n\tbytes_gpu\x18\x04 \x01(\x04\x12\x11\n\tbytes_ram\x18\x05 \x01(\x04\x12\x12\n\nbytes_disk\x18\x06 \x01(\x04\x62\x06proto3')
)




_STATSREQUEST = _descriptor.Descriptor(
  name='StatsRequest',
  full_name='payload.manager.admin.v1.StatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=80,
)


_STATSRESPONSE = _descriptor.Descriptor(
  name='StatsResponse',
  full_name='payload.manager.admin.v1.StatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payloads_gpu', full_name='payload.manager.admin.v1.StatsResponse.payloads_gpu', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payloads_ram', full_name='payload.manager.admin.v1.StatsResponse.payloads_ram', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payloads_disk', full_name='payload.manager.admin.v1.StatsResponse.payloads_disk', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_gpu', full_name='payload.manager.admin.v1.StatsResponse.bytes_gpu', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_ram', full_name='payload.manager.admin.v1.StatsResponse.bytes_ram', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_disk', full_name='payload.manager.admin.v1.StatsResponse.bytes_disk', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=223,
)

DESCRIPTOR.message_types_by_name['StatsRequest'] = _STATSREQUEST
DESCRIPTOR.message_types_by_name['StatsResponse'] = _STATSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATSREQUEST,
  __module__ = 'payload.manager.admin.v1.stats_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.admin.v1.StatsRequest)
  ))
_sym_db.RegisterMessage(StatsRequest)

StatsResponse = _reflection.GeneratedProtocolMessageType('StatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATSRESPONSE,
  __module__ = 'payload.manager.admin.v1.stats_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.admin.v1.StatsResponse)
  ))
_sym_db.RegisterMessage(StatsResponse)


# @@protoc_insertion_point(module_scope)
