# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/runtime/v1/lease.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/runtime/v1/lease.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import placement_pb2 as payload_dot_manager_dot_core_dot_v1_dot_placement__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&payload/manager/runtime/v1/lease.proto\x12\x1apayload.manager.runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\'payload/manager/core/v1/placement.proto\x1a$payload/manager/core/v1/policy.proto\x1a#payload/manager/core/v1/types.proto\x1a payload/manager/core/v1/id.proto\"H\n\x16ResolveSnapshotRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\"a\n\x17ResolveSnapshotResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"\x92\x02\n\x17\x41\x63quireReadLeaseRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12/\n\x08min_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x42\n\x10promotion_policy\x18\x03 \x01(\x0e\x32(.payload.manager.core.v1.PromotionPolicy\x12\x1d\n\x15min_lease_duration_ms\x18\x04 \x01(\x04\x12\x33\n\x04mode\x18\x05 \x01(\x0e\x32%.payload.manager.runtime.v1.LeaseMode\"\xcc\x01\n\x18\x41\x63quireReadLeaseResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\x12\x32\n\x08lease_id\x18\x02 \x01(\x0b\x32 .payload.manager.core.v1.LeaseID\x12\x34\n\x10lease_expires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"I\n\x13ReleaseLeaseRequest\x12\x32\n\x08lease_id\x18\x01 \x01(\x0b\x32 .payload.manager.core.v1.LeaseID*<\n\tLeaseMode\x12\x1a\n\x16LEASE_MODE_UNSPECIFIED\x10\x00\x12\x13\n\x0fLEASE_MODE_READ\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.runtime.v1.lease_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEASEMODE']._serialized_start=985
  _globals['_LEASEMODE']._serialized_end=1045
  _globals['_RESOLVESNAPSHOTREQUEST']._serialized_start=253
  _globals['_RESOLVESNAPSHOTREQUEST']._serialized_end=325
  _globals['_RESOLVESNAPSHOTRESPONSE']._serialized_start=327
  _globals['_RESOLVESNAPSHOTRESPONSE']._serialized_end=424
  _globals['_ACQUIREREADLEASEREQUEST']._serialized_start=427
  _globals['_ACQUIREREADLEASEREQUEST']._serialized_end=701
  _globals['_ACQUIREREADLEASERESPONSE']._serialized_start=704
  _globals['_ACQUIREREADLEASERESPONSE']._serialized_end=908
  _globals['_RELEASELEASEREQUEST']._serialized_start=910
  _globals['_RELEASELEASEREQUEST']._serialized_end=983
# @@protoc_insertion_point(module_scope)
