# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/runtime/v1/lease.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import placement_pb2 as payload_dot_manager_dot_core_dot_v1_dot_placement__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/runtime/v1/lease.proto',
  package='payload.manager.runtime.v1',
  syntax='proto3',
  serialized_pb=_b('\n&payload/manager/runtime/v1/lease.proto\x12\x1apayload.manager.runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\'payload/manager/core/v1/placement.proto\x1a$payload/manager/core/v1/policy.proto\x1a#payload/manager/core/v1/types.proto\x1a payload/manager/core/v1/id.proto\"H\n\x16ResolveSnapshotRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\"a\n\x17ResolveSnapshotResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"\x92\x02\n\x17\x41\x63quireReadLeaseRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12/\n\x08min_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x42\n\x10promotion_policy\x18\x03 \x01(\x0e\x32(.payload.manager.core.v1.PromotionPolicy\x12\x1d\n\x15min_lease_duration_ms\x18\x04 \x01(\x04\x12\x33\n\x04mode\x18\x05 \x01(\x0e\x32%.payload.manager.runtime.v1.LeaseMode\"\xcc\x01\n\x18\x41\x63quireReadLeaseResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\x12\x32\n\x08lease_id\x18\x02 \x01(\x0b\x32 .payload.manager.core.v1.LeaseID\x12\x34\n\x10lease_expires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"I\n\x13ReleaseLeaseRequest\x12\x32\n\x08lease_id\x18\x01 \x01(\x0b\x32 .payload.manager.core.v1.LeaseID*<\n\tLeaseMode\x12\x1a\n\x16LEASE_MODE_UNSPECIFIED\x10\x00\x12\x13\n\x0fLEASE_MODE_READ\x10\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_placement__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_policy__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_types__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,])

_LEASEMODE = _descriptor.EnumDescriptor(
  name='LeaseMode',
  full_name='payload.manager.runtime.v1.LeaseMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEASE_MODE_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEASE_MODE_READ', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=985,
  serialized_end=1045,
)
_sym_db.RegisterEnumDescriptor(_LEASEMODE)

LeaseMode = enum_type_wrapper.EnumTypeWrapper(_LEASEMODE)
LEASE_MODE_UNSPECIFIED = 0
LEASE_MODE_READ = 1



_RESOLVESNAPSHOTREQUEST = _descriptor.Descriptor(
  name='ResolveSnapshotRequest',
  full_name='payload.manager.runtime.v1.ResolveSnapshotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.ResolveSnapshotRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=325,
)


_RESOLVESNAPSHOTRESPONSE = _descriptor.Descriptor(
  name='ResolveSnapshotResponse',
  full_name='payload.manager.runtime.v1.ResolveSnapshotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.ResolveSnapshotResponse.payload_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=424,
)


_ACQUIREREADLEASEREQUEST = _descriptor.Descriptor(
  name='AcquireReadLeaseRequest',
  full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_tier', full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest.min_tier', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='promotion_policy', full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest.promotion_policy', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_lease_duration_ms', full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest.min_lease_duration_ms', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='payload.manager.runtime.v1.AcquireReadLeaseRequest.mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=701,
)


_ACQUIREREADLEASERESPONSE = _descriptor.Descriptor(
  name='AcquireReadLeaseResponse',
  full_name='payload.manager.runtime.v1.AcquireReadLeaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.AcquireReadLeaseResponse.payload_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lease_id', full_name='payload.manager.runtime.v1.AcquireReadLeaseResponse.lease_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lease_expires_at', full_name='payload.manager.runtime.v1.AcquireReadLeaseResponse.lease_expires_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=908,
)


_RELEASELEASEREQUEST = _descriptor.Descriptor(
  name='ReleaseLeaseRequest',
  full_name='payload.manager.runtime.v1.ReleaseLeaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lease_id', full_name='payload.manager.runtime.v1.ReleaseLeaseRequest.lease_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=910,
  serialized_end=983,
)

_RESOLVESNAPSHOTREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_RESOLVESNAPSHOTRESPONSE.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_ACQUIREREADLEASEREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_ACQUIREREADLEASEREQUEST.fields_by_name['min_tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_ACQUIREREADLEASEREQUEST.fields_by_name['promotion_policy'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._PROMOTIONPOLICY
_ACQUIREREADLEASEREQUEST.fields_by_name['mode'].enum_type = _LEASEMODE
_ACQUIREREADLEASERESPONSE.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_ACQUIREREADLEASERESPONSE.fields_by_name['lease_id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._LEASEID
_ACQUIREREADLEASERESPONSE.fields_by_name['lease_expires_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RELEASELEASEREQUEST.fields_by_name['lease_id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._LEASEID
DESCRIPTOR.message_types_by_name['ResolveSnapshotRequest'] = _RESOLVESNAPSHOTREQUEST
DESCRIPTOR.message_types_by_name['ResolveSnapshotResponse'] = _RESOLVESNAPSHOTRESPONSE
DESCRIPTOR.message_types_by_name['AcquireReadLeaseRequest'] = _ACQUIREREADLEASEREQUEST
DESCRIPTOR.message_types_by_name['AcquireReadLeaseResponse'] = _ACQUIREREADLEASERESPONSE
DESCRIPTOR.message_types_by_name['ReleaseLeaseRequest'] = _RELEASELEASEREQUEST
DESCRIPTOR.enum_types_by_name['LeaseMode'] = _LEASEMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResolveSnapshotRequest = _reflection.GeneratedProtocolMessageType('ResolveSnapshotRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESOLVESNAPSHOTREQUEST,
  __module__ = 'payload.manager.runtime.v1.lease_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.ResolveSnapshotRequest)
  ))
_sym_db.RegisterMessage(ResolveSnapshotRequest)

ResolveSnapshotResponse = _reflection.GeneratedProtocolMessageType('ResolveSnapshotResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESOLVESNAPSHOTRESPONSE,
  __module__ = 'payload.manager.runtime.v1.lease_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.ResolveSnapshotResponse)
  ))
_sym_db.RegisterMessage(ResolveSnapshotResponse)

AcquireReadLeaseRequest = _reflection.GeneratedProtocolMessageType('AcquireReadLeaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACQUIREREADLEASEREQUEST,
  __module__ = 'payload.manager.runtime.v1.lease_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.AcquireReadLeaseRequest)
  ))
_sym_db.RegisterMessage(AcquireReadLeaseRequest)

AcquireReadLeaseResponse = _reflection.GeneratedProtocolMessageType('AcquireReadLeaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACQUIREREADLEASERESPONSE,
  __module__ = 'payload.manager.runtime.v1.lease_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.AcquireReadLeaseResponse)
  ))
_sym_db.RegisterMessage(AcquireReadLeaseResponse)

ReleaseLeaseRequest = _reflection.GeneratedProtocolMessageType('ReleaseLeaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _RELEASELEASEREQUEST,
  __module__ = 'payload.manager.runtime.v1.lease_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.ReleaseLeaseRequest)
  ))
_sym_db.RegisterMessage(ReleaseLeaseRequest)


# @@protoc_insertion_point(module_scope)
