# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/runtime/v1/lifecycle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import placement_pb2 as payload_dot_manager_dot_core_dot_v1_dot_placement__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/runtime/v1/lifecycle.proto',
  package='payload.manager.runtime.v1',
  syntax='proto3',
  serialized_pb=_b('\n*payload/manager/runtime/v1/lifecycle.proto\x12\x1apayload.manager.runtime.v1\x1a\'payload/manager/core/v1/placement.proto\x1a payload/manager/core/v1/id.proto\x1a#payload/manager/core/v1/types.proto\x1a$payload/manager/core/v1/policy.proto\"\xc6\x01\n\x16\x41llocatePayloadRequest\x12\x12\n\nsize_bytes\x18\x01 \x01(\x04\x12\x35\n\x0epreferred_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x0e\n\x06ttl_ms\x18\x03 \x01(\x04\x12\x0f\n\x07persist\x18\x04 \x01(\x08\x12@\n\x0f\x65viction_policy\x18\x05 \x01(\x0b\x32\'.payload.manager.core.v1.EvictionPolicy\"a\n\x17\x41llocatePayloadResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"F\n\x14\x43ommitPayloadRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\"_\n\x15\x43ommitPayloadResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"N\n\rDeleteRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[payload_dot_manager_dot_core_dot_v1_dot_placement__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_types__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_policy__pb2.DESCRIPTOR,])




_ALLOCATEPAYLOADREQUEST = _descriptor.Descriptor(
  name='AllocatePayloadRequest',
  full_name='payload.manager.runtime.v1.AllocatePayloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size_bytes', full_name='payload.manager.runtime.v1.AllocatePayloadRequest.size_bytes', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preferred_tier', full_name='payload.manager.runtime.v1.AllocatePayloadRequest.preferred_tier', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl_ms', full_name='payload.manager.runtime.v1.AllocatePayloadRequest.ttl_ms', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='persist', full_name='payload.manager.runtime.v1.AllocatePayloadRequest.persist', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eviction_policy', full_name='payload.manager.runtime.v1.AllocatePayloadRequest.eviction_policy', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=423,
)


_ALLOCATEPAYLOADRESPONSE = _descriptor.Descriptor(
  name='AllocatePayloadResponse',
  full_name='payload.manager.runtime.v1.AllocatePayloadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.AllocatePayloadResponse.payload_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=522,
)


_COMMITPAYLOADREQUEST = _descriptor.Descriptor(
  name='CommitPayloadRequest',
  full_name='payload.manager.runtime.v1.CommitPayloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.CommitPayloadRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=594,
)


_COMMITPAYLOADRESPONSE = _descriptor.Descriptor(
  name='CommitPayloadResponse',
  full_name='payload.manager.runtime.v1.CommitPayloadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.CommitPayloadResponse.payload_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=691,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='payload.manager.runtime.v1.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.DeleteRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='payload.manager.runtime.v1.DeleteRequest.force', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=693,
  serialized_end=771,
)

_ALLOCATEPAYLOADREQUEST.fields_by_name['preferred_tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_ALLOCATEPAYLOADREQUEST.fields_by_name['eviction_policy'].message_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._EVICTIONPOLICY
_ALLOCATEPAYLOADRESPONSE.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_COMMITPAYLOADREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_COMMITPAYLOADRESPONSE.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_DELETEREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
DESCRIPTOR.message_types_by_name['AllocatePayloadRequest'] = _ALLOCATEPAYLOADREQUEST
DESCRIPTOR.message_types_by_name['AllocatePayloadResponse'] = _ALLOCATEPAYLOADRESPONSE
DESCRIPTOR.message_types_by_name['CommitPayloadRequest'] = _COMMITPAYLOADREQUEST
DESCRIPTOR.message_types_by_name['CommitPayloadResponse'] = _COMMITPAYLOADRESPONSE
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllocatePayloadRequest = _reflection.GeneratedProtocolMessageType('AllocatePayloadRequest', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATEPAYLOADREQUEST,
  __module__ = 'payload.manager.runtime.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.AllocatePayloadRequest)
  ))
_sym_db.RegisterMessage(AllocatePayloadRequest)

AllocatePayloadResponse = _reflection.GeneratedProtocolMessageType('AllocatePayloadResponse', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATEPAYLOADRESPONSE,
  __module__ = 'payload.manager.runtime.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.AllocatePayloadResponse)
  ))
_sym_db.RegisterMessage(AllocatePayloadResponse)

CommitPayloadRequest = _reflection.GeneratedProtocolMessageType('CommitPayloadRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMITPAYLOADREQUEST,
  __module__ = 'payload.manager.runtime.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.CommitPayloadRequest)
  ))
_sym_db.RegisterMessage(CommitPayloadRequest)

CommitPayloadResponse = _reflection.GeneratedProtocolMessageType('CommitPayloadResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMMITPAYLOADRESPONSE,
  __module__ = 'payload.manager.runtime.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.CommitPayloadResponse)
  ))
_sym_db.RegisterMessage(CommitPayloadResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'payload.manager.runtime.v1.lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)


# @@protoc_insertion_point(module_scope)
