# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/runtime/v1/ring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/runtime/v1/ring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%payload/manager/runtime/v1/ring.proto\x12\x1apayload.manager.runtime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#payload/manager/core/v1/types.proto\")\n\x16\x41\x63quireRingSlotRequest\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\"i\n\x17\x41\x63quireRingSlotResponse\x12\x10\n\x08slot_idx\x18\x01 \x01(\r\x12\x12\n\ngeneration\x18\x02 \x01(\x04\x12\x10\n\x08shm_name\x18\x03 \x01(\t\x12\x16\n\x0e\x63\x61pacity_bytes\x18\x04 \x01(\x04\"b\n\x15\x43ommitRingSlotRequest\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\x12\x10\n\x08slot_idx\x18\x02 \x01(\r\x12\x12\n\ngeneration\x18\x03 \x01(\x04\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04\"J\n\x16\x43ommitRingSlotResponse\x12\x30\n\x0c\x63ommitted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"!\n\x0eMapRingRequest\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\"\x8c\x01\n\x0fMapRingResponse\x12\x0f\n\x07n_slots\x18\x01 \x01(\r\x12\x1b\n\x13slot_capacity_bytes\x18\x02 \x01(\x04\x12\x16\n\x0eslot_shm_names\x18\x03 \x03(\t\x12\x33\n\x0c\x62\x61\x63king_tier\x18\x04 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\"M\n\x14LeaseRingSlotRequest\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\x12\x10\n\x08slot_idx\x18\x02 \x01(\r\x12\x12\n\ngeneration\x18\x03 \x01(\x04\"O\n\x15LeaseRingSlotResponse\x12\x10\n\x08lease_id\x18\x01 \x01(\x0c\x12\x10\n\x08slot_idx\x18\x02 \x01(\r\x12\x12\n\ngeneration\x18\x03 \x01(\x04\"*\n\x16ReleaseRingSlotRequest\x12\x10\n\x08lease_id\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.runtime.v1.ring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACQUIRERINGSLOTREQUEST']._serialized_start=139
  _globals['_ACQUIRERINGSLOTREQUEST']._serialized_end=180
  _globals['_ACQUIRERINGSLOTRESPONSE']._serialized_start=182
  _globals['_ACQUIRERINGSLOTRESPONSE']._serialized_end=287
  _globals['_COMMITRINGSLOTREQUEST']._serialized_start=289
  _globals['_COMMITRINGSLOTREQUEST']._serialized_end=387
  _globals['_COMMITRINGSLOTRESPONSE']._serialized_start=389
  _globals['_COMMITRINGSLOTRESPONSE']._serialized_end=463
  _globals['_MAPRINGREQUEST']._serialized_start=465
  _globals['_MAPRINGREQUEST']._serialized_end=498
  _globals['_MAPRINGRESPONSE']._serialized_start=501
  _globals['_MAPRINGRESPONSE']._serialized_end=641
  _globals['_LEASERINGSLOTREQUEST']._serialized_start=643
  _globals['_LEASERINGSLOTREQUEST']._serialized_end=720
  _globals['_LEASERINGSLOTRESPONSE']._serialized_start=722
  _globals['_LEASERINGSLOTRESPONSE']._serialized_end=801
  _globals['_RELEASERINGSLOTREQUEST']._serialized_start=803
  _globals['_RELEASERINGSLOTREQUEST']._serialized_end=845
# @@protoc_insertion_point(module_scope)
