# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/runtime/v1/tiering.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/runtime/v1/tiering.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import placement_pb2 as payload_dot_manager_dot_core_dot_v1_dot_placement__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(payload/manager/runtime/v1/tiering.proto\x12\x1apayload.manager.runtime.v1\x1a\'payload/manager/core/v1/placement.proto\x1a$payload/manager/core/v1/policy.proto\x1a#payload/manager/core/v1/types.proto\x1a payload/manager/core/v1/id.proto\"\xae\x01\n\x0ePromoteRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x32\n\x0btarget_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x38\n\x06policy\x18\x03 \x01(\x0e\x32(.payload.manager.core.v1.PromotionPolicy\"Y\n\x0fPromoteResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"\xd1\x01\n\x0cSpillRequest\x12/\n\x03ids\x18\x01 \x03(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x34\n\x06policy\x18\x02 \x01(\x0e\x32$.payload.manager.core.v1.SpillPolicy\x12\x17\n\x0fwait_for_leases\x18\x03 \x01(\x08\x12\r\n\x05\x66sync\x18\x04 \x01(\x08\x12\x32\n\x0btarget_tier\x18\x05 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\"\xf8\x01\n\rSpillResponse\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.payload.manager.runtime.v1.SpillResponse.Result\x1a\xa3\x01\n\x06Result\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x46\n\x12payload_descriptor\x18\x04 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"u\n\x0fPrefetchRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x32\n\x0btarget_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\"Q\n\nPinRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x04\">\n\x0cUnpinRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadIDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.runtime.v1.tiering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMOTEREQUEST']._serialized_start=223
  _globals['_PROMOTEREQUEST']._serialized_end=397
  _globals['_PROMOTERESPONSE']._serialized_start=399
  _globals['_PROMOTERESPONSE']._serialized_end=488
  _globals['_SPILLREQUEST']._serialized_start=491
  _globals['_SPILLREQUEST']._serialized_end=700
  _globals['_SPILLRESPONSE']._serialized_start=703
  _globals['_SPILLRESPONSE']._serialized_end=951
  _globals['_SPILLRESPONSE_RESULT']._serialized_start=788
  _globals['_SPILLRESPONSE_RESULT']._serialized_end=951
  _globals['_PREFETCHREQUEST']._serialized_start=953
  _globals['_PREFETCHREQUEST']._serialized_end=1070
  _globals['_PINREQUEST']._serialized_start=1072
  _globals['_PINREQUEST']._serialized_end=1153
  _globals['_UNPINREQUEST']._serialized_start=1155
  _globals['_UNPINREQUEST']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
