# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/runtime/v1/tiering.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import placement_pb2 as payload_dot_manager_dot_core_dot_v1_dot_placement__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/runtime/v1/tiering.proto',
  package='payload.manager.runtime.v1',
  syntax='proto3',
  serialized_pb=_b('\n(payload/manager/runtime/v1/tiering.proto\x12\x1apayload.manager.runtime.v1\x1a\'payload/manager/core/v1/placement.proto\x1a$payload/manager/core/v1/policy.proto\x1a#payload/manager/core/v1/types.proto\x1a payload/manager/core/v1/id.proto\"\xae\x01\n\x0ePromoteRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x32\n\x0btarget_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x38\n\x06policy\x18\x03 \x01(\x0e\x32(.payload.manager.core.v1.PromotionPolicy\"Y\n\x0fPromoteResponse\x12\x46\n\x12payload_descriptor\x18\x01 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"\x9d\x01\n\x0cSpillRequest\x12/\n\x03ids\x18\x01 \x03(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x34\n\x06policy\x18\x02 \x01(\x0e\x32$.payload.manager.core.v1.SpillPolicy\x12\x17\n\x0fwait_for_leases\x18\x03 \x01(\x08\x12\r\n\x05\x66sync\x18\x04 \x01(\x08\"\xf8\x01\n\rSpillResponse\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.payload.manager.runtime.v1.SpillResponse.Result\x1a\xa3\x01\n\x06Result\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x46\n\x12payload_descriptor\x18\x04 \x01(\x0b\x32*.payload.manager.core.v1.PayloadDescriptor\"u\n\x0fPrefetchRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x32\n\x0btarget_tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\"Q\n\nPinRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x04\">\n\x0cUnpinRequest\x12.\n\x02id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadIDb\x06proto3')
  ,
  dependencies=[payload_dot_manager_dot_core_dot_v1_dot_placement__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_policy__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_types__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,])




_PROMOTEREQUEST = _descriptor.Descriptor(
  name='PromoteRequest',
  full_name='payload.manager.runtime.v1.PromoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.PromoteRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_tier', full_name='payload.manager.runtime.v1.PromoteRequest.target_tier', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='payload.manager.runtime.v1.PromoteRequest.policy', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=397,
)


_PROMOTERESPONSE = _descriptor.Descriptor(
  name='PromoteResponse',
  full_name='payload.manager.runtime.v1.PromoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.PromoteResponse.payload_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=488,
)


_SPILLREQUEST = _descriptor.Descriptor(
  name='SpillRequest',
  full_name='payload.manager.runtime.v1.SpillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='payload.manager.runtime.v1.SpillRequest.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='payload.manager.runtime.v1.SpillRequest.policy', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wait_for_leases', full_name='payload.manager.runtime.v1.SpillRequest.wait_for_leases', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fsync', full_name='payload.manager.runtime.v1.SpillRequest.fsync', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=648,
)


_SPILLRESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='payload.manager.runtime.v1.SpillResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.SpillResponse.Result.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok', full_name='payload.manager.runtime.v1.SpillResponse.Result.ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='payload.manager.runtime.v1.SpillResponse.Result.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='payload.manager.runtime.v1.SpillResponse.Result.payload_descriptor', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=736,
  serialized_end=899,
)

_SPILLRESPONSE = _descriptor.Descriptor(
  name='SpillResponse',
  full_name='payload.manager.runtime.v1.SpillResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='payload.manager.runtime.v1.SpillResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPILLRESPONSE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=651,
  serialized_end=899,
)


_PREFETCHREQUEST = _descriptor.Descriptor(
  name='PrefetchRequest',
  full_name='payload.manager.runtime.v1.PrefetchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.PrefetchRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_tier', full_name='payload.manager.runtime.v1.PrefetchRequest.target_tier', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=901,
  serialized_end=1018,
)


_PINREQUEST = _descriptor.Descriptor(
  name='PinRequest',
  full_name='payload.manager.runtime.v1.PinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.PinRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_ms', full_name='payload.manager.runtime.v1.PinRequest.duration_ms', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1020,
  serialized_end=1101,
)


_UNPINREQUEST = _descriptor.Descriptor(
  name='UnpinRequest',
  full_name='payload.manager.runtime.v1.UnpinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='payload.manager.runtime.v1.UnpinRequest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1103,
  serialized_end=1165,
)

_PROMOTEREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_PROMOTEREQUEST.fields_by_name['target_tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_PROMOTEREQUEST.fields_by_name['policy'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._PROMOTIONPOLICY
_PROMOTERESPONSE.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_SPILLREQUEST.fields_by_name['ids'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_SPILLREQUEST.fields_by_name['policy'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._SPILLPOLICY
_SPILLRESPONSE_RESULT.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_SPILLRESPONSE_RESULT.fields_by_name['payload_descriptor'].message_type = payload_dot_manager_dot_core_dot_v1_dot_placement__pb2._PAYLOADDESCRIPTOR
_SPILLRESPONSE_RESULT.containing_type = _SPILLRESPONSE
_SPILLRESPONSE.fields_by_name['results'].message_type = _SPILLRESPONSE_RESULT
_PREFETCHREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_PREFETCHREQUEST.fields_by_name['target_tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_PINREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_UNPINREQUEST.fields_by_name['id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
DESCRIPTOR.message_types_by_name['PromoteRequest'] = _PROMOTEREQUEST
DESCRIPTOR.message_types_by_name['PromoteResponse'] = _PROMOTERESPONSE
DESCRIPTOR.message_types_by_name['SpillRequest'] = _SPILLREQUEST
DESCRIPTOR.message_types_by_name['SpillResponse'] = _SPILLRESPONSE
DESCRIPTOR.message_types_by_name['PrefetchRequest'] = _PREFETCHREQUEST
DESCRIPTOR.message_types_by_name['PinRequest'] = _PINREQUEST
DESCRIPTOR.message_types_by_name['UnpinRequest'] = _UNPINREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PromoteRequest = _reflection.GeneratedProtocolMessageType('PromoteRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROMOTEREQUEST,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.PromoteRequest)
  ))
_sym_db.RegisterMessage(PromoteRequest)

PromoteResponse = _reflection.GeneratedProtocolMessageType('PromoteResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROMOTERESPONSE,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.PromoteResponse)
  ))
_sym_db.RegisterMessage(PromoteResponse)

SpillRequest = _reflection.GeneratedProtocolMessageType('SpillRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPILLREQUEST,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.SpillRequest)
  ))
_sym_db.RegisterMessage(SpillRequest)

SpillResponse = _reflection.GeneratedProtocolMessageType('SpillResponse', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _SPILLRESPONSE_RESULT,
    __module__ = 'payload.manager.runtime.v1.tiering_pb2'
    # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.SpillResponse.Result)
    ))
  ,
  DESCRIPTOR = _SPILLRESPONSE,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.SpillResponse)
  ))
_sym_db.RegisterMessage(SpillResponse)
_sym_db.RegisterMessage(SpillResponse.Result)

PrefetchRequest = _reflection.GeneratedProtocolMessageType('PrefetchRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREFETCHREQUEST,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.PrefetchRequest)
  ))
_sym_db.RegisterMessage(PrefetchRequest)

PinRequest = _reflection.GeneratedProtocolMessageType('PinRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINREQUEST,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.PinRequest)
  ))
_sym_db.RegisterMessage(PinRequest)

UnpinRequest = _reflection.GeneratedProtocolMessageType('UnpinRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNPINREQUEST,
  __module__ = 'payload.manager.runtime.v1.tiering_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.runtime.v1.UnpinRequest)
  ))
_sym_db.RegisterMessage(UnpinRequest)


# @@protoc_insertion_point(module_scope)
