# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/core/v1/id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/core/v1/id.proto',
  package='payload.manager.core.v1',
  syntax='proto3',
  serialized_pb=_b('\n payload/manager/core/v1/id.proto\x12\x17payload.manager.core.v1\"\x1a\n\tPayloadID\x12\r\n\x05value\x18\x01 \x01(\x0c\"\x18\n\x07LeaseID\x12\r\n\x05value\x18\x01 \x01(\x0c\x62\x06proto3')
)




_PAYLOADID = _descriptor.Descriptor(
  name='PayloadID',
  full_name='payload.manager.core.v1.PayloadID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='payload.manager.core.v1.PayloadID.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=87,
)


_LEASEID = _descriptor.Descriptor(
  name='LeaseID',
  full_name='payload.manager.core.v1.LeaseID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='payload.manager.core.v1.LeaseID.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['PayloadID'] = _PAYLOADID
DESCRIPTOR.message_types_by_name['LeaseID'] = _LEASEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PayloadID = _reflection.GeneratedProtocolMessageType('PayloadID', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOADID,
  __module__ = 'payload.manager.core.v1.id_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.PayloadID)
  ))
_sym_db.RegisterMessage(PayloadID)

LeaseID = _reflection.GeneratedProtocolMessageType('LeaseID', (_message.Message,), dict(
  DESCRIPTOR = _LEASEID,
  __module__ = 'payload.manager.core.v1.id_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.LeaseID)
  ))
_sym_db.RegisterMessage(LeaseID)


# @@protoc_insertion_point(module_scope)
