# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/core/v1/placement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/core/v1/placement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'payload/manager/core/v1/placement.proto\x12\x17payload.manager.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#payload/manager/core/v1/types.proto\x1a$payload/manager/core/v1/policy.proto\x1a payload/manager/core/v1/id.proto\"J\n\x0bGpuLocation\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x12\n\nipc_handle\x18\x02 \x01(\x0c\x12\x14\n\x0clength_bytes\x18\x03 \x01(\x04\"[\n\x0bRamLocation\x12\x10\n\x08shm_name\x18\x01 \x01(\t\x12\x0f\n\x07slab_id\x18\x02 \x01(\r\x12\x13\n\x0b\x62lock_index\x18\x03 \x01(\x04\x12\x14\n\x0clength_bytes\x18\x04 \x01(\x04\"H\n\x0c\x44iskLocation\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x14\n\x0coffset_bytes\x18\x02 \x01(\x04\x12\x14\n\x0clength_bytes\x18\x03 \x01(\x04\"\x8e\x04\n\x11PayloadDescriptor\x12\x36\n\npayload_id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12+\n\x04tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x34\n\x05state\x18\x03 \x01(\x0e\x32%.payload.manager.core.v1.PayloadState\x12\x33\n\x03gpu\x18\x04 \x01(\x0b\x32$.payload.manager.core.v1.GpuLocationH\x00\x12\x33\n\x03ram\x18\x05 \x01(\x0b\x32$.payload.manager.core.v1.RamLocationH\x00\x12\x35\n\x04\x64isk\x18\x06 \x01(\x0b\x32%.payload.manager.core.v1.DiskLocationH\x00\x12\x0f\n\x07version\x18\x07 \x01(\x04\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x0f\x65viction_policy\x18\n \x01(\x0b\x32\'.payload.manager.core.v1.EvictionPolicyB\n\n\x08locationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.core.v1.placement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPULOCATION']._serialized_start=210
  _globals['_GPULOCATION']._serialized_end=284
  _globals['_RAMLOCATION']._serialized_start=286
  _globals['_RAMLOCATION']._serialized_end=377
  _globals['_DISKLOCATION']._serialized_start=379
  _globals['_DISKLOCATION']._serialized_end=451
  _globals['_PAYLOADDESCRIPTOR']._serialized_start=454
  _globals['_PAYLOADDESCRIPTOR']._serialized_end=980
# @@protoc_insertion_point(module_scope)
