# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/core/v1/placement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2
from payload.manager.core.v1 import policy_pb2 as payload_dot_manager_dot_core_dot_v1_dot_policy__pb2
from payload.manager.core.v1 import id_pb2 as payload_dot_manager_dot_core_dot_v1_dot_id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/core/v1/placement.proto',
  package='payload.manager.core.v1',
  syntax='proto3',
  serialized_pb=_b('\n\'payload/manager/core/v1/placement.proto\x12\x17payload.manager.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#payload/manager/core/v1/types.proto\x1a$payload/manager/core/v1/policy.proto\x1a payload/manager/core/v1/id.proto\"J\n\x0bGpuLocation\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x12\n\nipc_handle\x18\x02 \x01(\x0c\x12\x14\n\x0clength_bytes\x18\x03 \x01(\x04\"[\n\x0bRamLocation\x12\x10\n\x08shm_name\x18\x01 \x01(\t\x12\x0f\n\x07slab_id\x18\x02 \x01(\r\x12\x13\n\x0b\x62lock_index\x18\x03 \x01(\x04\x12\x14\n\x0clength_bytes\x18\x04 \x01(\x04\"H\n\x0c\x44iskLocation\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x14\n\x0coffset_bytes\x18\x02 \x01(\x04\x12\x14\n\x0clength_bytes\x18\x03 \x01(\x04\"\x8e\x04\n\x11PayloadDescriptor\x12\x36\n\npayload_id\x18\x01 \x01(\x0b\x32\".payload.manager.core.v1.PayloadID\x12+\n\x04tier\x18\x02 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x34\n\x05state\x18\x03 \x01(\x0e\x32%.payload.manager.core.v1.PayloadState\x12\x33\n\x03gpu\x18\x04 \x01(\x0b\x32$.payload.manager.core.v1.GpuLocationH\x00\x12\x33\n\x03ram\x18\x05 \x01(\x0b\x32$.payload.manager.core.v1.RamLocationH\x00\x12\x35\n\x04\x64isk\x18\x06 \x01(\x0b\x32%.payload.manager.core.v1.DiskLocationH\x00\x12\x0f\n\x07version\x18\x07 \x01(\x04\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x0f\x65viction_policy\x18\n \x01(\x0b\x32\'.payload.manager.core.v1.EvictionPolicyB\n\n\x08locationb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_types__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_policy__pb2.DESCRIPTOR,payload_dot_manager_dot_core_dot_v1_dot_id__pb2.DESCRIPTOR,])




_GPULOCATION = _descriptor.Descriptor(
  name='GpuLocation',
  full_name='payload.manager.core.v1.GpuLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='payload.manager.core.v1.GpuLocation.device_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipc_handle', full_name='payload.manager.core.v1.GpuLocation.ipc_handle', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_bytes', full_name='payload.manager.core.v1.GpuLocation.length_bytes', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=284,
)


_RAMLOCATION = _descriptor.Descriptor(
  name='RamLocation',
  full_name='payload.manager.core.v1.RamLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shm_name', full_name='payload.manager.core.v1.RamLocation.shm_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slab_id', full_name='payload.manager.core.v1.RamLocation.slab_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_index', full_name='payload.manager.core.v1.RamLocation.block_index', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_bytes', full_name='payload.manager.core.v1.RamLocation.length_bytes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=377,
)


_DISKLOCATION = _descriptor.Descriptor(
  name='DiskLocation',
  full_name='payload.manager.core.v1.DiskLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='payload.manager.core.v1.DiskLocation.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset_bytes', full_name='payload.manager.core.v1.DiskLocation.offset_bytes', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_bytes', full_name='payload.manager.core.v1.DiskLocation.length_bytes', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=451,
)


_PAYLOADDESCRIPTOR = _descriptor.Descriptor(
  name='PayloadDescriptor',
  full_name='payload.manager.core.v1.PayloadDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_id', full_name='payload.manager.core.v1.PayloadDescriptor.payload_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tier', full_name='payload.manager.core.v1.PayloadDescriptor.tier', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='payload.manager.core.v1.PayloadDescriptor.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='payload.manager.core.v1.PayloadDescriptor.gpu', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram', full_name='payload.manager.core.v1.PayloadDescriptor.ram', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk', full_name='payload.manager.core.v1.PayloadDescriptor.disk', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='payload.manager.core.v1.PayloadDescriptor.version', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='payload.manager.core.v1.PayloadDescriptor.created_at', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expires_at', full_name='payload.manager.core.v1.PayloadDescriptor.expires_at', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eviction_policy', full_name='payload.manager.core.v1.PayloadDescriptor.eviction_policy', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='location', full_name='payload.manager.core.v1.PayloadDescriptor.location',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=454,
  serialized_end=980,
)

_PAYLOADDESCRIPTOR.fields_by_name['payload_id'].message_type = payload_dot_manager_dot_core_dot_v1_dot_id__pb2._PAYLOADID
_PAYLOADDESCRIPTOR.fields_by_name['tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_PAYLOADDESCRIPTOR.fields_by_name['state'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._PAYLOADSTATE
_PAYLOADDESCRIPTOR.fields_by_name['gpu'].message_type = _GPULOCATION
_PAYLOADDESCRIPTOR.fields_by_name['ram'].message_type = _RAMLOCATION
_PAYLOADDESCRIPTOR.fields_by_name['disk'].message_type = _DISKLOCATION
_PAYLOADDESCRIPTOR.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PAYLOADDESCRIPTOR.fields_by_name['expires_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PAYLOADDESCRIPTOR.fields_by_name['eviction_policy'].message_type = payload_dot_manager_dot_core_dot_v1_dot_policy__pb2._EVICTIONPOLICY
_PAYLOADDESCRIPTOR.oneofs_by_name['location'].fields.append(
  _PAYLOADDESCRIPTOR.fields_by_name['gpu'])
_PAYLOADDESCRIPTOR.fields_by_name['gpu'].containing_oneof = _PAYLOADDESCRIPTOR.oneofs_by_name['location']
_PAYLOADDESCRIPTOR.oneofs_by_name['location'].fields.append(
  _PAYLOADDESCRIPTOR.fields_by_name['ram'])
_PAYLOADDESCRIPTOR.fields_by_name['ram'].containing_oneof = _PAYLOADDESCRIPTOR.oneofs_by_name['location']
_PAYLOADDESCRIPTOR.oneofs_by_name['location'].fields.append(
  _PAYLOADDESCRIPTOR.fields_by_name['disk'])
_PAYLOADDESCRIPTOR.fields_by_name['disk'].containing_oneof = _PAYLOADDESCRIPTOR.oneofs_by_name['location']
DESCRIPTOR.message_types_by_name['GpuLocation'] = _GPULOCATION
DESCRIPTOR.message_types_by_name['RamLocation'] = _RAMLOCATION
DESCRIPTOR.message_types_by_name['DiskLocation'] = _DISKLOCATION
DESCRIPTOR.message_types_by_name['PayloadDescriptor'] = _PAYLOADDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpuLocation = _reflection.GeneratedProtocolMessageType('GpuLocation', (_message.Message,), dict(
  DESCRIPTOR = _GPULOCATION,
  __module__ = 'payload.manager.core.v1.placement_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.GpuLocation)
  ))
_sym_db.RegisterMessage(GpuLocation)

RamLocation = _reflection.GeneratedProtocolMessageType('RamLocation', (_message.Message,), dict(
  DESCRIPTOR = _RAMLOCATION,
  __module__ = 'payload.manager.core.v1.placement_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.RamLocation)
  ))
_sym_db.RegisterMessage(RamLocation)

DiskLocation = _reflection.GeneratedProtocolMessageType('DiskLocation', (_message.Message,), dict(
  DESCRIPTOR = _DISKLOCATION,
  __module__ = 'payload.manager.core.v1.placement_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.DiskLocation)
  ))
_sym_db.RegisterMessage(DiskLocation)

PayloadDescriptor = _reflection.GeneratedProtocolMessageType('PayloadDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOADDESCRIPTOR,
  __module__ = 'payload.manager.core.v1.placement_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.PayloadDescriptor)
  ))
_sym_db.RegisterMessage(PayloadDescriptor)


# @@protoc_insertion_point(module_scope)
