# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/core/v1/policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/core/v1/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$payload/manager/core/v1/policy.proto\x12\x17payload.manager.core.v1\x1a#payload/manager/core/v1/types.proto\"\xd6\x01\n\x0e\x45victionPolicy\x12;\n\x08priority\x18\x01 \x01(\x0e\x32).payload.manager.core.v1.EvictionPriority\x12\x17\n\x0frequire_durable\x18\x02 \x01(\x08\x12\x33\n\x0cspill_target\x18\x03 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x39\n\x12min_residency_tier\x18\x04 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier*t\n\x0fPromotionPolicy\x12 \n\x1cPROMOTION_POLICY_UNSPECIFIED\x10\x00\x12 \n\x1cPROMOTION_POLICY_BEST_EFFORT\x10\x01\x12\x1d\n\x19PROMOTION_POLICY_BLOCKING\x10\x02*d\n\x0bSpillPolicy\x12\x1c\n\x18SPILL_POLICY_UNSPECIFIED\x10\x00\x12\x1c\n\x18SPILL_POLICY_BEST_EFFORT\x10\x01\x12\x19\n\x15SPILL_POLICY_BLOCKING\x10\x02*|\n\x12MetadataUpdateMode\x12$\n METADATA_UPDATE_MODE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aMETADATA_UPDATE_MODE_MERGE\x10\x01\x12 \n\x1cMETADATA_UPDATE_MODE_REPLACE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.core.v1.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMOTIONPOLICY']._serialized_start=319
  _globals['_PROMOTIONPOLICY']._serialized_end=435
  _globals['_SPILLPOLICY']._serialized_start=437
  _globals['_SPILLPOLICY']._serialized_end=537
  _globals['_METADATAUPDATEMODE']._serialized_start=539
  _globals['_METADATAUPDATEMODE']._serialized_end=663
  _globals['_EVICTIONPOLICY']._serialized_start=103
  _globals['_EVICTIONPOLICY']._serialized_end=317
# @@protoc_insertion_point(module_scope)
