# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/core/v1/policy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload.manager.core.v1 import types_pb2 as payload_dot_manager_dot_core_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/core/v1/policy.proto',
  package='payload.manager.core.v1',
  syntax='proto3',
  serialized_pb=_b('\n$payload/manager/core/v1/policy.proto\x12\x17payload.manager.core.v1\x1a#payload/manager/core/v1/types.proto\"\xd6\x01\n\x0e\x45victionPolicy\x12;\n\x08priority\x18\x01 \x01(\x0e\x32).payload.manager.core.v1.EvictionPriority\x12\x17\n\x0frequire_durable\x18\x02 \x01(\x08\x12\x33\n\x0cspill_target\x18\x03 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier\x12\x39\n\x12min_residency_tier\x18\x04 \x01(\x0e\x32\x1d.payload.manager.core.v1.Tier*t\n\x0fPromotionPolicy\x12 \n\x1cPROMOTION_POLICY_UNSPECIFIED\x10\x00\x12 \n\x1cPROMOTION_POLICY_BEST_EFFORT\x10\x01\x12\x1d\n\x19PROMOTION_POLICY_BLOCKING\x10\x02*d\n\x0bSpillPolicy\x12\x1c\n\x18SPILL_POLICY_UNSPECIFIED\x10\x00\x12\x1c\n\x18SPILL_POLICY_BEST_EFFORT\x10\x01\x12\x19\n\x15SPILL_POLICY_BLOCKING\x10\x02*|\n\x12MetadataUpdateMode\x12$\n METADATA_UPDATE_MODE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aMETADATA_UPDATE_MODE_MERGE\x10\x01\x12 \n\x1cMETADATA_UPDATE_MODE_REPLACE\x10\x02\x62\x06proto3')
  ,
  dependencies=[payload_dot_manager_dot_core_dot_v1_dot_types__pb2.DESCRIPTOR,])

_PROMOTIONPOLICY = _descriptor.EnumDescriptor(
  name='PromotionPolicy',
  full_name='payload.manager.core.v1.PromotionPolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROMOTION_POLICY_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROMOTION_POLICY_BEST_EFFORT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROMOTION_POLICY_BLOCKING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=319,
  serialized_end=435,
)
_sym_db.RegisterEnumDescriptor(_PROMOTIONPOLICY)

PromotionPolicy = enum_type_wrapper.EnumTypeWrapper(_PROMOTIONPOLICY)
_SPILLPOLICY = _descriptor.EnumDescriptor(
  name='SpillPolicy',
  full_name='payload.manager.core.v1.SpillPolicy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SPILL_POLICY_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPILL_POLICY_BEST_EFFORT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPILL_POLICY_BLOCKING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=437,
  serialized_end=537,
)
_sym_db.RegisterEnumDescriptor(_SPILLPOLICY)

SpillPolicy = enum_type_wrapper.EnumTypeWrapper(_SPILLPOLICY)
_METADATAUPDATEMODE = _descriptor.EnumDescriptor(
  name='MetadataUpdateMode',
  full_name='payload.manager.core.v1.MetadataUpdateMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METADATA_UPDATE_MODE_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METADATA_UPDATE_MODE_MERGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METADATA_UPDATE_MODE_REPLACE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=539,
  serialized_end=663,
)
_sym_db.RegisterEnumDescriptor(_METADATAUPDATEMODE)

MetadataUpdateMode = enum_type_wrapper.EnumTypeWrapper(_METADATAUPDATEMODE)
PROMOTION_POLICY_UNSPECIFIED = 0
PROMOTION_POLICY_BEST_EFFORT = 1
PROMOTION_POLICY_BLOCKING = 2
SPILL_POLICY_UNSPECIFIED = 0
SPILL_POLICY_BEST_EFFORT = 1
SPILL_POLICY_BLOCKING = 2
METADATA_UPDATE_MODE_UNSPECIFIED = 0
METADATA_UPDATE_MODE_MERGE = 1
METADATA_UPDATE_MODE_REPLACE = 2



_EVICTIONPOLICY = _descriptor.Descriptor(
  name='EvictionPolicy',
  full_name='payload.manager.core.v1.EvictionPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='payload.manager.core.v1.EvictionPolicy.priority', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='require_durable', full_name='payload.manager.core.v1.EvictionPolicy.require_durable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spill_target', full_name='payload.manager.core.v1.EvictionPolicy.spill_target', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_residency_tier', full_name='payload.manager.core.v1.EvictionPolicy.min_residency_tier', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=317,
)

_EVICTIONPOLICY.fields_by_name['priority'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._EVICTIONPRIORITY
_EVICTIONPOLICY.fields_by_name['spill_target'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
_EVICTIONPOLICY.fields_by_name['min_residency_tier'].enum_type = payload_dot_manager_dot_core_dot_v1_dot_types__pb2._TIER
DESCRIPTOR.message_types_by_name['EvictionPolicy'] = _EVICTIONPOLICY
DESCRIPTOR.enum_types_by_name['PromotionPolicy'] = _PROMOTIONPOLICY
DESCRIPTOR.enum_types_by_name['SpillPolicy'] = _SPILLPOLICY
DESCRIPTOR.enum_types_by_name['MetadataUpdateMode'] = _METADATAUPDATEMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EvictionPolicy = _reflection.GeneratedProtocolMessageType('EvictionPolicy', (_message.Message,), dict(
  DESCRIPTOR = _EVICTIONPOLICY,
  __module__ = 'payload.manager.core.v1.policy_pb2'
  # @@protoc_insertion_point(class_scope:payload.manager.core.v1.EvictionPolicy)
  ))
_sym_db.RegisterMessage(EvictionPolicy)


# @@protoc_insertion_point(module_scope)
