# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/manager/core/v1/ring_slot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/manager/core/v1/ring_slot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'payload/manager/core/v1/ring_slot.proto\x12\x17payload.manager.core.v1\"X\n\x0bRingSlotRef\x12\x0f\n\x07ring_id\x18\x01 \x01(\t\x12\x10\n\x08slot_idx\x18\x02 \x01(\r\x12\x12\n\ngeneration\x18\x03 \x01(\x04\x12\x12\n\nsize_bytes\x18\x04 \x01(\x04*\x85\x01\n\x14RingExhaustionPolicy\x12&\n\"RING_EXHAUSTION_POLICY_UNSPECIFIED\x10\x00\x12#\n\x1fRING_EXHAUSTION_POLICY_DROP_NEW\x10\x01\x12 \n\x1cRING_EXHAUSTION_POLICY_BLOCK\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.manager.core.v1.ring_slot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RINGEXHAUSTIONPOLICY']._serialized_start=159
  _globals['_RINGEXHAUSTIONPOLICY']._serialized_end=292
  _globals['_RINGSLOTREF']._serialized_start=68
  _globals['_RINGSLOTREF']._serialized_end=156
# @@protoc_insertion_point(module_scope)
