# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload/manager/core/v1/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload/manager/core/v1/types.proto',
  package='payload.manager.core.v1',
  syntax='proto3',
  serialized_pb=_b('\n#payload/manager/core/v1/types.proto\x12\x17payload.manager.core.v1*X\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\x0c\n\x08TIER_GPU\x10\x01\x12\x0c\n\x08TIER_RAM\x10\x02\x12\r\n\tTIER_DISK\x10\x03\x12\x0f\n\x0bTIER_OBJECT\x10\x04*\x89\x02\n\x0cPayloadState\x12\x1d\n\x19PAYLOAD_STATE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PAYLOAD_STATE_ALLOCATED\x10\x01\x12\x18\n\x14PAYLOAD_STATE_ACTIVE\x10\x02\x12\x1a\n\x16PAYLOAD_STATE_SPILLING\x10\x03\x12\x19\n\x15PAYLOAD_STATE_DURABLE\x10\x04\x12\x1a\n\x16PAYLOAD_STATE_EVICTING\x10\x05\x12\x1a\n\x16PAYLOAD_STATE_DELETING\x10\x06\x12\x19\n\x15PAYLOAD_STATE_EXPIRED\x10\x07\x12\x19\n\x15PAYLOAD_STATE_DELETED\x10\x08*\xa7\x01\n\x10\x45victionPriority\x12!\n\x1d\x45VICTION_PRIORITY_UNSPECIFIED\x10\x00\x12\x19\n\x15\x45VICTION_PRIORITY_LOW\x10\x01\x12\x1c\n\x18\x45VICTION_PRIORITY_NORMAL\x10\x02\x12\x1a\n\x16\x45VICTION_PRIORITY_HIGH\x10\x03\x12\x1b\n\x17\x45VICTION_PRIORITY_NEVER\x10\x04\x62\x06proto3')
)

_TIER = _descriptor.EnumDescriptor(
  name='Tier',
  full_name='payload.manager.core.v1.Tier',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIER_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIER_GPU', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIER_RAM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIER_DISK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIER_OBJECT', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=64,
  serialized_end=152,
)
_sym_db.RegisterEnumDescriptor(_TIER)

Tier = enum_type_wrapper.EnumTypeWrapper(_TIER)
_PAYLOADSTATE = _descriptor.EnumDescriptor(
  name='PayloadState',
  full_name='payload.manager.core.v1.PayloadState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_ALLOCATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_ACTIVE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_SPILLING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_DURABLE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_EVICTING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_DELETING', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_EXPIRED', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_STATE_DELETED', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=155,
  serialized_end=420,
)
_sym_db.RegisterEnumDescriptor(_PAYLOADSTATE)

PayloadState = enum_type_wrapper.EnumTypeWrapper(_PAYLOADSTATE)
_EVICTIONPRIORITY = _descriptor.EnumDescriptor(
  name='EvictionPriority',
  full_name='payload.manager.core.v1.EvictionPriority',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EVICTION_PRIORITY_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVICTION_PRIORITY_LOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVICTION_PRIORITY_NORMAL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVICTION_PRIORITY_HIGH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVICTION_PRIORITY_NEVER', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=423,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_EVICTIONPRIORITY)

EvictionPriority = enum_type_wrapper.EnumTypeWrapper(_EVICTIONPRIORITY)
TIER_UNSPECIFIED = 0
TIER_GPU = 1
TIER_RAM = 2
TIER_DISK = 3
TIER_OBJECT = 4
PAYLOAD_STATE_UNSPECIFIED = 0
PAYLOAD_STATE_ALLOCATED = 1
PAYLOAD_STATE_ACTIVE = 2
PAYLOAD_STATE_SPILLING = 3
PAYLOAD_STATE_DURABLE = 4
PAYLOAD_STATE_EVICTING = 5
PAYLOAD_STATE_DELETING = 6
PAYLOAD_STATE_EXPIRED = 7
PAYLOAD_STATE_DELETED = 8
EVICTION_PRIORITY_UNSPECIFIED = 0
EVICTION_PRIORITY_LOW = 1
EVICTION_PRIORITY_NORMAL = 2
EVICTION_PRIORITY_HIGH = 3
EVICTION_PRIORITY_NEVER = 4


DESCRIPTOR.enum_types_by_name['Tier'] = _TIER
DESCRIPTOR.enum_types_by_name['PayloadState'] = _PAYLOADSTATE
DESCRIPTOR.enum_types_by_name['EvictionPriority'] = _EVICTIONPRIORITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
